// Generated by ReScript, PLEASE EDIT WITH CARE


function toPascalCase(str) {
  return str.replaceAll("-", " ").replaceAll("_", " ").replaceAll("/", " ").split(" ").filter(part => part !== "").map(part => part.charAt(0).toUpperCase() + part.substring(1).toLowerCase()).join("");
}

function toCamelCase(str) {
  let pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.substring(1);
}

function sanitizeIdentifier(str) {
  return str.replaceAll("{", "").replaceAll("}", "").replaceAll("[", "").replaceAll("]", "").replaceAll(".", "_").replaceAll("-", "_").replaceAll("/", "_").replaceAll(" ", "_");
}

function generateTypeName(prefixOpt, path, suffix) {
  let prefix = prefixOpt !== undefined ? prefixOpt : "";
  let cleaned = sanitizeIdentifier(path.replaceAll("/", "_")).split("_").filter(part => part !== "").map(toPascalCase).join("");
  return prefix + cleaned + suffix;
}

function generateOperationName(operationId, path, method) {
  if (operationId !== undefined) {
    return toCamelCase(sanitizeIdentifier(operationId));
  }
  let methodStr = method.toLowerCase();
  let pathPart = path.split("/").filter(part => {
    if (part !== "") {
      return !part.startsWith("{");
    } else {
      return false;
    }
  }).map(toCamelCase).join("");
  return methodStr + pathPart;
}

function escapeString(str) {
  return str.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("\t", "\\t");
}

function generateFileHeader(description) {
  return `// SPDX-License-Identifier: MIT
// ` + description + `
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated

`;
}

function indent(code, level) {
  let spaces = "  ".repeat(level);
  return code.split("\n").map(line => {
    if (line.trim() === "") {
      return "";
    } else {
      return spaces + line;
    }
  }).join("\n");
}

let rescriptKeywords = [
  "and",
  "as",
  "assert",
  "async",
  "await",
  "catch",
  "class",
  "constraint",
  "do",
  "done",
  "downto",
  "else",
  "end",
  "exception",
  "external",
  "false",
  "for",
  "fun",
  "function",
  "functor",
  "if",
  "in",
  "include",
  "inherit",
  "initializer",
  "lazy",
  "let",
  "method",
  "module",
  "mutable",
  "new",
  "nonrec",
  "object",
  "of",
  "open",
  "or",
  "private",
  "rec",
  "sig",
  "struct",
  "switch",
  "then",
  "to",
  "true",
  "try",
  "type",
  "val",
  "virtual",
  "when",
  "while",
  "with"
];

function escapeKeyword(name) {
  if (rescriptKeywords.includes(name)) {
    return name + "_";
  } else {
    return name;
  }
}

function generateDocComment(summary, description, param) {
  if (summary !== undefined) {
    if (description !== undefined) {
      return `// ` + summary + `\n// ` + description + `\n`;
    } else {
      return `// ` + summary + `\n`;
    }
  } else if (description !== undefined) {
    return `// ` + description + `\n`;
  } else {
    return "";
  }
}

export {
  toPascalCase,
  toCamelCase,
  sanitizeIdentifier,
  generateTypeName,
  generateOperationName,
  escapeString,
  generateFileHeader,
  indent,
  rescriptKeywords,
  escapeKeyword,
  generateDocComment,
}
/* No side effect */
