// Generated by ReScript, PLEASE EDIT WITH CARE


let empty_files = [];

let empty_warnings = [];

let empty = {
  files: empty_files,
  warnings: empty_warnings
};

function combine(outputs) {
  let allFiles = [];
  let allWarnings = [];
  outputs.forEach(output => {
    allFiles.push(...output.files);
    allWarnings.push(...output.warnings);
  });
  return {
    files: allFiles,
    warnings: allWarnings
  };
}

function withWarnings(output, warnings) {
  return {
    files: output.files,
    warnings: output.warnings.concat(warnings)
  };
}

function withFiles(output, files) {
  return {
    files: output.files.concat(files),
    warnings: output.warnings
  };
}

function fromFile(file) {
  return {
    files: [file],
    warnings: []
  };
}

function fromFilesAndWarnings(files, warnings) {
  return {
    files: files,
    warnings: warnings
  };
}

function mapFiles(output, fn) {
  return {
    files: output.files.map(fn),
    warnings: output.warnings
  };
}

function filterWarnings(output, predicate) {
  return {
    files: output.files,
    warnings: output.warnings.filter(predicate)
  };
}

function fileCount(output) {
  return output.files.length;
}

function warningCount(output) {
  return output.warnings.length;
}

function filePaths(output) {
  return output.files.map(file => file.path);
}

export {
  empty,
  combine,
  withWarnings,
  withFiles,
  fromFile,
  fromFilesAndWarnings,
  mapFiles,
  filterWarnings,
  fileCount,
  warningCount,
  filePaths,
}
/* No side effect */
