// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CodegenUtils from "./CodegenUtils.mjs";

function refToTypePath(insideComponentSchemasOpt, ref) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let parts = ref.split("/");
  let schemaName = parts[parts.length - 1 | 0];
  if (schemaName === undefined) {
    return;
  }
  let moduleName = CodegenUtils.toPascalCase(schemaName);
  if (insideComponentSchemas) {
    return moduleName + `.t`;
  } else {
    return `ComponentSchemas.` + moduleName + `.t`;
  }
}

function refToSchemaPath(insideComponentSchemasOpt, ref) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let parts = ref.split("/");
  let schemaName = parts[parts.length - 1 | 0];
  if (schemaName === undefined) {
    return;
  }
  let moduleName = CodegenUtils.toPascalCase(schemaName);
  if (insideComponentSchemas) {
    return moduleName + `.schema`;
  } else {
    return `ComponentSchemas.` + moduleName + `.schema`;
  }
}

export {
  refToTypePath,
  refToSchemaPath,
}
/* No side effect */
