// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SchemaIR from "./SchemaIR.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parseTypeString(rawType) {
  switch (rawType) {
    case "array" :
      return {
        TAG: "Array",
        _0: "Unknown"
      };
    case "boolean" :
      return "Boolean";
    case "integer" :
      return "Integer";
    case "null" :
      return "Null";
    case "number" :
      return "Number";
    case "object" :
      return "Object";
    case "string" :
      return "String";
    default:
      switch (rawType) {
        case "Boolean" :
          return "Boolean";
        case "Integer" :
          return "Integer";
        case "Null" :
          return "Null";
        case "Number" :
          return "Number";
        case "Object" :
          return "Object";
        case "String" :
          return "String";
        default:
          return "Unknown";
      }
  }
}

function addWarning(ctx, warning) {
  ctx.warnings.push(warning);
}

function parseJsonSchemaWithContext(ctx, depthOpt, schema) {
  let depth = depthOpt !== undefined ? depthOpt : 0;
  if (depth > 30) {
    addWarning(ctx, {
      TAG: "DepthLimitReached",
      depth: depth,
      path: ctx.path
    });
    return "Unknown";
  }
  let ref = schema.$ref;
  if (ref !== undefined) {
    return {
      TAG: "Reference",
      _0: ref
    };
  }
  let isNullable = Stdlib_Option.getOr(schema.nullable, false);
  let normalizedType = Stdlib_Option.map(schema.type, parseTypeString);
  let baseType;
  if (normalizedType !== undefined) {
    if (typeof normalizedType !== "object") {
      switch (normalizedType) {
        case "String" :
          let constraints_minLength = schema.minLength;
          let constraints_maxLength = schema.maxLength;
          let constraints_pattern = schema.pattern;
          let constraints = {
            minLength: constraints_minLength,
            maxLength: constraints_maxLength,
            pattern: constraints_pattern
          };
          baseType = {
            TAG: "String",
            constraints: constraints
          };
          break;
        case "Number" :
          let constraints_minimum = schema.minimum;
          let constraints_maximum = schema.maximum;
          let constraints$1 = {
            minimum: constraints_minimum,
            maximum: constraints_maximum,
            multipleOf: undefined
          };
          baseType = {
            TAG: "Number",
            constraints: constraints$1
          };
          break;
        case "Integer" :
          let constraints_minimum$1 = schema.minimum;
          let constraints_maximum$1 = schema.maximum;
          let constraints$2 = {
            minimum: constraints_minimum$1,
            maximum: constraints_maximum$1,
            multipleOf: undefined
          };
          baseType = {
            TAG: "Integer",
            constraints: constraints$2
          };
          break;
        case "Boolean" :
          baseType = "Boolean";
          break;
        case "Object" :
          let propsDict = schema.properties;
          let properties;
          if (propsDict !== undefined) {
            let required = Stdlib_Option.getOr(schema.required, []);
            properties = Object.entries(propsDict).map(param => {
              let name = param[0];
              let isRequired = required.includes(name);
              let propType = parseJsonSchemaWithContext(ctx, depth + 1 | 0, param[1]);
              return [
                name,
                propType,
                isRequired
              ];
            });
          } else {
            properties = [];
          }
          baseType = {
            TAG: "Object",
            properties: properties,
            additionalProperties: undefined
          };
          break;
        case "Null" :
          baseType = "Null";
          break;
        case "Unknown" :
          baseType = "Unknown";
          break;
      }
    } else {
      let itemSchema = schema.items;
      let items = itemSchema !== undefined ? parseJsonSchemaWithContext(ctx, depth + 1 | 0, itemSchema) : "Unknown";
      baseType = {
        TAG: "Array",
        items: items,
        constraints: {
          minItems: undefined,
          maxItems: undefined,
          uniqueItems: false
        }
      };
    }
  } else {
    let match = schema.enum;
    let match$1 = schema.properties;
    let match$2 = schema.allOf;
    let match$3 = schema.oneOf;
    let match$4 = schema.anyOf;
    if (match !== undefined) {
      let literals = match.map(value => {
        if (value === null) {
          return {
            TAG: "Literal",
            _0: "NullLiteral"
          };
        }
        if (Array.isArray(value)) {
          return "Unknown";
        }
        switch (typeof value) {
          case "boolean" :
            return {
              TAG: "Literal",
              _0: {
                TAG: "BooleanLiteral",
                _0: value
              }
            };
          case "string" :
            return {
              TAG: "Literal",
              _0: {
                TAG: "StringLiteral",
                _0: value
              }
            };
          case "number" :
            return {
              TAG: "Literal",
              _0: {
                TAG: "NumberLiteral",
                _0: value
              }
            };
          case "object" :
            return "Unknown";
        }
      });
      baseType = {
        TAG: "Union",
        _0: literals
      };
    } else if (match$1 !== undefined) {
      baseType = parseJsonSchemaWithContext(ctx, depth + 1 | 0, {
        type: "Object",
        properties: schema.properties,
        items: schema.items,
        required: schema.required,
        enum: schema.enum,
        $ref: schema.$ref,
        allOf: schema.allOf,
        oneOf: schema.oneOf,
        anyOf: schema.anyOf,
        description: schema.description,
        format: schema.format,
        minLength: schema.minLength,
        maxLength: schema.maxLength,
        minimum: schema.minimum,
        maximum: schema.maximum,
        pattern: schema.pattern,
        nullable: schema.nullable
      });
    } else if (match$2 !== undefined) {
      let types = match$2.map(s => parseJsonSchemaWithContext(ctx, depth + 1 | 0, s));
      baseType = {
        TAG: "Intersection",
        _0: types
      };
    } else if (match$3 !== undefined) {
      let types$1 = match$3.map(s => parseJsonSchemaWithContext(ctx, depth + 1 | 0, s));
      baseType = {
        TAG: "Union",
        _0: types$1
      };
    } else if (match$4 !== undefined) {
      let types$2 = match$4.map(s => parseJsonSchemaWithContext(ctx, depth + 1 | 0, s));
      baseType = {
        TAG: "Union",
        _0: types$2
      };
    } else {
      baseType = "Unknown";
    }
  }
  if (isNullable) {
    return {
      TAG: "Option",
      _0: baseType
    };
  } else {
    return baseType;
  }
}

function parseJsonSchema(depthOpt, schema) {
  let depth = depthOpt !== undefined ? depthOpt : 0;
  let ctx = {
    warnings: [],
    path: "root"
  };
  let irType = parseJsonSchemaWithContext(ctx, depth, schema);
  return [
    irType,
    ctx.warnings
  ];
}

function parseNamedSchema(name, schema) {
  let ctx = {
    warnings: [],
    path: `components.schemas.` + name
  };
  let type_ = parseJsonSchemaWithContext(ctx, undefined, schema);
  return [
    {
      name: name,
      description: schema.description,
      type_: type_
    },
    ctx.warnings
  ];
}

function parseComponentSchemas(schemas) {
  let namedSchemas = {};
  let allWarnings = [];
  Object.entries(schemas).forEach(param => {
    let name = param[0];
    let match = parseNamedSchema(name, param[1]);
    namedSchemas[name] = match[0];
    allWarnings.push(...match[1]);
  });
  return [
    {
      schemas: namedSchemas
    },
    allWarnings
  ];
}

function resolveReference(context, ref) {
  let parts = ref.split("/");
  let schemaName = parts[parts.length - 1 | 0];
  if (schemaName !== undefined) {
    return context.schemas[schemaName];
  }
}

function inlineSimpleReferences(context, _irType, _depthOpt, _maxDepthOpt) {
  while (true) {
    let depthOpt = _depthOpt;
    let maxDepthOpt = _maxDepthOpt;
    let irType = _irType;
    let depth = depthOpt !== undefined ? depthOpt : 0;
    let maxDepth = maxDepthOpt !== undefined ? maxDepthOpt : 2;
    if (depth >= maxDepth) {
      return irType;
    }
    if (typeof irType !== "object") {
      return irType;
    }
    switch (irType.TAG) {
      case "Array" :
        return {
          TAG: "Array",
          items: inlineSimpleReferences(context, irType.items, depth, maxDepth),
          constraints: irType.constraints
        };
      case "Object" :
        let newProperties = irType.properties.map(param => [
          param[0],
          inlineSimpleReferences(context, param[1], depth, maxDepth),
          param[2]
        ]);
        let newAdditionalProps = Stdlib_Option.map(irType.additionalProperties, type_ => inlineSimpleReferences(context, type_, depth, maxDepth));
        return {
          TAG: "Object",
          properties: newProperties,
          additionalProperties: newAdditionalProps
        };
      case "Union" :
        return {
          TAG: "Union",
          _0: irType._0.map(type_ => inlineSimpleReferences(context, type_, depth, maxDepth))
        };
      case "Intersection" :
        return {
          TAG: "Intersection",
          _0: irType._0.map(type_ => inlineSimpleReferences(context, type_, depth, maxDepth))
        };
      case "Reference" :
        let schema = resolveReference(context, irType._0);
        if (schema === undefined) {
          return irType;
        }
        if (!SchemaIR.isSimpleType(schema.type_)) {
          return irType;
        }
        _maxDepthOpt = maxDepth;
        _depthOpt = depth + 1 | 0;
        _irType = schema.type_;
        continue;
      case "Option" :
        return {
          TAG: "Option",
          _0: inlineSimpleReferences(context, irType._0, depth, maxDepth)
        };
      default:
        return irType;
    }
  };
}

function optimizeIR(irType) {
  if (typeof irType !== "object") {
    return irType;
  }
  switch (irType.TAG) {
    case "Array" :
      return {
        TAG: "Array",
        items: optimizeIR(irType.items),
        constraints: irType.constraints
      };
    case "Object" :
      let newProperties = irType.properties.map(param => [
        param[0],
        optimizeIR(param[1]),
        param[2]
      ]);
      let newAdditionalProps = Stdlib_Option.map(irType.additionalProperties, optimizeIR);
      return {
        TAG: "Object",
        properties: newProperties,
        additionalProperties: newAdditionalProps
      };
    case "Union" :
      let flattened = irType._0.flatMap(t => {
        let inner = optimizeIR(t);
        if (typeof inner !== "object") {
          return [inner];
        } else if (inner.TAG === "Union") {
          return inner._0;
        } else {
          return [inner];
        }
      });
      let unique = Stdlib_Array.reduce(flattened, [], (acc, type_) => {
        let typeStr = SchemaIR.toString(type_);
        let exists = acc.some(t => SchemaIR.toString(t) === typeStr);
        if (exists) {
          return acc;
        } else {
          return acc.concat([type_]);
        }
      });
      let len = unique.length;
      if (len !== 1) {
        if (len !== 0) {
          return {
            TAG: "Union",
            _0: unique
          };
        } else {
          return "Unknown";
        }
      } else {
        return unique[0];
      }
    case "Intersection" :
      let flattened$1 = irType._0.flatMap(t => {
        let inner = optimizeIR(t);
        if (typeof inner !== "object") {
          return [inner];
        } else if (inner.TAG === "Intersection") {
          return inner._0;
        } else {
          return [inner];
        }
      });
      let len$1 = flattened$1.length;
      if (len$1 !== 1) {
        if (len$1 !== 0) {
          return {
            TAG: "Intersection",
            _0: flattened$1
          };
        } else {
          return "Unknown";
        }
      } else {
        return flattened$1[0];
      }
    case "Option" :
      return {
        TAG: "Option",
        _0: optimizeIR(irType._0)
      };
    default:
      return irType;
  }
}

export {
  parseTypeString,
  addWarning,
  parseJsonSchemaWithContext,
  parseJsonSchema,
  parseNamedSchema,
  parseComponentSchemas,
  resolveReference,
  inlineSimpleReferences,
  optimizeIR,
}
/* No side effect */
