// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as SpecDiffer from "./SpecDiffer.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function makeEndpointKey(endpoint) {
  return endpoint.method + `:` + endpoint.path;
}

function extractSharedEndpoints(baseEndpoints, forkEndpoints) {
  let forkMap = {};
  Belt_Array.forEach(forkEndpoints, ep => {
    let key = makeEndpointKey(ep);
    forkMap[key] = ep;
  });
  return Belt_Array.keep(baseEndpoints, baseEp => {
    let key = makeEndpointKey(baseEp);
    let forkEp = forkMap[key];
    if (forkEp === undefined) {
      return false;
    }
    let match = SpecDiffer.compareEndpoints(baseEp, forkEp);
    return match === undefined;
  });
}

function extractForkExtensions(baseEndpoints, forkEndpoints) {
  let baseMap = {};
  Belt_Array.forEach(baseEndpoints, ep => {
    let key = makeEndpointKey(ep);
    baseMap[key] = ep;
  });
  return Belt_Array.keep(forkEndpoints, forkEp => {
    let key = makeEndpointKey(forkEp);
    let baseEp = baseMap[key];
    if (baseEp !== undefined) {
      return SpecDiffer.compareEndpoints(baseEp, forkEp) !== undefined;
    } else {
      return true;
    }
  });
}

function extractSharedSchemas(baseSchemas, forkSchemas) {
  if (baseSchemas === undefined) {
    return;
  }
  if (forkSchemas === undefined) {
    return;
  }
  let shared = {};
  Belt_Array.forEach(Object.keys(baseSchemas), name => {
    let match = baseSchemas[name];
    let match$1 = forkSchemas[name];
    if (match !== undefined && match$1 !== undefined && SpecDiffer.schemasEqual(match, match$1)) {
      shared[name] = match;
      return;
    }
  });
  if (Object.keys(shared).length !== 0) {
    return shared;
  }
}

function extractForkSchemas(baseSchemas, forkSchemas) {
  if (forkSchemas === undefined) {
    return;
  }
  if (baseSchemas === undefined) {
    return forkSchemas;
  }
  let extensions = {};
  Belt_Array.forEach(Object.keys(forkSchemas), name => {
    let match = baseSchemas[name];
    let match$1 = forkSchemas[name];
    if (match !== undefined) {
      if (match$1 !== undefined && !SpecDiffer.schemasEqual(match, match$1)) {
        extensions[name] = match$1;
        return;
      } else {
        return;
      }
    } else if (match$1 !== undefined) {
      extensions[name] = match$1;
      return;
    } else {
      return;
    }
  });
  if (Object.keys(extensions).length !== 0) {
    return extensions;
  }
}

function createSpecWithEndpoints(baseSpec, endpoints, schemas) {
  let pathsDict = {};
  Belt_Array.forEach(endpoints, ep => {
    let existing = pathsDict[ep.path];
    let pathItem = existing !== undefined ? existing : ({
        get: undefined,
        post: undefined,
        put: undefined,
        patch: undefined,
        delete: undefined,
        head: undefined,
        options: undefined,
        parameters: undefined
      });
    let operation_operationId = ep.operationId;
    let operation_summary = ep.summary;
    let operation_description = ep.description;
    let operation_tags = ep.tags;
    let operation_requestBody = ep.requestBody;
    let operation_responses = ep.responses;
    let operation_parameters = ep.parameters;
    let operation = {
      operationId: operation_operationId,
      summary: operation_summary,
      description: operation_description,
      tags: operation_tags,
      requestBody: operation_requestBody,
      responses: operation_responses,
      parameters: operation_parameters
    };
    let match = ep.method.toLowerCase();
    let updatedPathItem;
    switch (match) {
      case "delete" :
        updatedPathItem = {
          get: pathItem.get,
          post: pathItem.post,
          put: pathItem.put,
          patch: pathItem.patch,
          delete: operation,
          head: pathItem.head,
          options: pathItem.options,
          parameters: pathItem.parameters
        };
        break;
      case "get" :
        updatedPathItem = {
          get: operation,
          post: pathItem.post,
          put: pathItem.put,
          patch: pathItem.patch,
          delete: pathItem.delete,
          head: pathItem.head,
          options: pathItem.options,
          parameters: pathItem.parameters
        };
        break;
      case "patch" :
        updatedPathItem = {
          get: pathItem.get,
          post: pathItem.post,
          put: pathItem.put,
          patch: operation,
          delete: pathItem.delete,
          head: pathItem.head,
          options: pathItem.options,
          parameters: pathItem.parameters
        };
        break;
      case "post" :
        updatedPathItem = {
          get: pathItem.get,
          post: operation,
          put: pathItem.put,
          patch: pathItem.patch,
          delete: pathItem.delete,
          head: pathItem.head,
          options: pathItem.options,
          parameters: pathItem.parameters
        };
        break;
      case "put" :
        updatedPathItem = {
          get: pathItem.get,
          post: pathItem.post,
          put: operation,
          patch: pathItem.patch,
          delete: pathItem.delete,
          head: pathItem.head,
          options: pathItem.options,
          parameters: pathItem.parameters
        };
        break;
      default:
        updatedPathItem = pathItem;
    }
    pathsDict[ep.path] = updatedPathItem;
  });
  let match = baseSpec.components;
  let components = match !== undefined ? (
      schemas !== undefined ? ({
          schemas: schemas
        }) : ({
          schemas: undefined
        })
    ) : (
      schemas !== undefined ? ({
          schemas: schemas
        }) : undefined
    );
  return {
    openapi: baseSpec.openapi,
    info: baseSpec.info,
    paths: pathsDict,
    components: components
  };
}

function mergeWithSharedBase(baseSpec, forkSpec, baseEndpoints, forkEndpoints) {
  let sharedEndpoints = extractSharedEndpoints(baseEndpoints, forkEndpoints);
  let forkExtensions = extractForkExtensions(baseEndpoints, forkEndpoints);
  let baseSchemas = Belt_Option.flatMap(baseSpec.components, c => c.schemas);
  let forkSchemas = Belt_Option.flatMap(forkSpec.components, c => c.schemas);
  let sharedSchemas = extractSharedSchemas(baseSchemas, forkSchemas);
  let extensionSchemas = extractForkSchemas(baseSchemas, forkSchemas);
  let sharedSpec = createSpecWithEndpoints(baseSpec, sharedEndpoints, sharedSchemas);
  let extensionsSpec = createSpecWithEndpoints(forkSpec, forkExtensions, extensionSchemas);
  return [
    sharedSpec,
    extensionsSpec
  ];
}

function mergeWithSeparate(baseSpec, forkSpec) {
  return [
    baseSpec,
    forkSpec
  ];
}

function mergeSpecs(baseSpec, forkSpec, baseEndpoints, forkEndpoints, strategy) {
  switch (strategy) {
    case "Separate" :
      return [
        baseSpec,
        forkSpec
      ];
    case "SharedBase" :
    case "ConditionalCompilation" :
      return mergeWithSharedBase(baseSpec, forkSpec, baseEndpoints, forkEndpoints);
  }
}

function getMergeStats(baseEndpoints, forkEndpoints, baseSchemas, forkSchemas) {
  let shared = extractSharedEndpoints(baseEndpoints, forkEndpoints);
  let extensions = extractForkExtensions(baseEndpoints, forkEndpoints);
  let sharedSchemas = extractSharedSchemas(baseSchemas, forkSchemas);
  let extensionSchemas = extractForkSchemas(baseSchemas, forkSchemas);
  return {
    sharedEndpointCount: shared.length,
    forkExtensionCount: extensions.length,
    sharedSchemaCount: Belt_Option.mapWithDefault(sharedSchemas, 0, s => Object.keys(s).length),
    forkSchemaCount: Belt_Option.mapWithDefault(extensionSchemas, 0, s => Object.keys(s).length)
  };
}

export {
  makeEndpointKey,
  extractSharedEndpoints,
  extractForkExtensions,
  extractSharedSchemas,
  extractForkSchemas,
  createSpecWithEndpoints,
  mergeWithSharedBase,
  mergeWithSeparate,
  mergeSpecs,
  getMergeStats,
}
/* No side effect */
