// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.mjs";
import * as FileSystem from "../core/FileSystem.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as SchemaIRParser from "../core/SchemaIRParser.mjs";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as IRToSuryGenerator from "./IRToSuryGenerator.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.mjs";

function extractReferences(_irType) {
  while (true) {
    let irType = _irType;
    if (typeof irType !== "object") {
      return [];
    }
    switch (irType.TAG) {
      case "Array" :
        _irType = irType.items;
        continue;
      case "Object" :
        return irType.properties.flatMap(param => extractReferences(param[1]));
      case "Union" :
      case "Intersection" :
        return irType._0.flatMap(extractReferences);
      case "Reference" :
        let parts = irType._0.split("/");
        let name = parts[parts.length - 1 | 0];
        if (name !== undefined) {
          return [name];
        } else {
          return [];
        }
      case "Option" :
        _irType = irType._0;
        continue;
      default:
        return [];
    }
  };
}

function generateComponentModule(namedSchema) {
  let allWarnings = [];
  let ctx = {
    warnings: [],
    path: `ComponentSchemas.` + namedSchema.name,
    insideComponentSchemas: true
  };
  let typeCode = IRToTypeGenerator.generateTypeWithContext(ctx, 0, namedSchema.type_);
  allWarnings.push(...ctx.warnings);
  let schemaCtx = {
    warnings: [],
    path: `ComponentSchemas.` + namedSchema.name,
    insideComponentSchemas: true
  };
  let schemaCode = IRToSuryGenerator.generateSchemaWithContext(schemaCtx, 0, namedSchema.type_);
  allWarnings.push(...schemaCtx.warnings);
  let typeName = CodegenUtils.toPascalCase(namedSchema.name);
  let desc = namedSchema.description;
  let doc = desc !== undefined ? CodegenUtils.generateDocComment(undefined, desc, undefined) : "";
  let moduleCode = doc + `module ` + typeName + ` = {
  type t = ` + typeCode + `
  
  let schema = ` + schemaCode + `
}`;
  return [
    moduleCode,
    allWarnings
  ];
}

function generateComponentSchemasModule(spec) {
  let allWarnings = [];
  let components = spec.components;
  let match;
  if (components !== undefined) {
    let schemas = components.schemas;
    match = schemas !== undefined ? SchemaIRParser.parseComponentSchemas(schemas) : [
        {
          schemas: {}
        },
        []
      ];
  } else {
    match = [
      {
        schemas: {}
      },
      []
    ];
  }
  allWarnings.push(...match[1]);
  let schemas$1 = Object.values(match[0].schemas);
  let schemaDict = Object.fromEntries(schemas$1.map(s => [
    s.name,
    s
  ]));
  let dependencies = {};
  schemas$1.forEach(schema => {
    let deps = extractReferences(schema.type_).filter(dep => dep in schemaDict);
    dependencies[schema.name] = deps;
  });
  let sorted = [];
  let inDegree = {};
  schemas$1.forEach(schema => {
    inDegree[schema.name] = 0;
  });
  schemas$1.forEach(schema => {
    let deps = Belt_Option.getWithDefault(dependencies[schema.name], []);
    deps.forEach(dep => {
      let current = Belt_Option.getWithDefault(inDegree[schema.name], 0);
      inDegree[schema.name] = current + 1 | 0;
    });
  });
  let queue = [];
  schemas$1.forEach(schema => {
    if (Belt_Option.getWithDefault(inDegree[schema.name], 0) === 0) {
      queue.push(schema);
      return;
    }
  });
  while (queue.length !== 0) {
    let schema = queue.shift();
    if (schema !== undefined) {
      sorted.push(schema);
      schemas$1.forEach(dependent => {
        let deps = Belt_Option.getWithDefault(dependencies[dependent.name], []);
        if (!deps.includes(schema.name)) {
          return;
        }
        let current = Belt_Option.getWithDefault(inDegree[dependent.name], 0);
        let newDegree = current - 1 | 0;
        inDegree[dependent.name] = newDegree;
        if (newDegree === 0) {
          queue.push(dependent);
          return;
        }
      });
    }
  };
  let sortedNames = sorted.map(s => s.name);
  let remaining = Belt_SortArray.stableSortBy(schemas$1.filter(s => !sortedNames.includes(s.name)), (a, b) => Primitive_string.compare(a.name, b.name));
  let sortedSchemas = sorted.concat(remaining);
  let componentModules = sortedSchemas.map(namedSchema => {
    let match = generateComponentModule(namedSchema);
    allWarnings.push(...match[1]);
    return match[0];
  });
  let header = CodegenUtils.generateFileHeader("Component Schemas - Shared types and validation schemas");
  let moduleContent = componentModules.length === 0 ? header + `

// No component schemas defined in the OpenAPI spec
` : header + `

` + componentModules.join("\n\n") + `
`;
  return [
    moduleContent,
    allWarnings
  ];
}

function hasComponentSchemas(spec) {
  let components = spec.components;
  if (components === undefined) {
    return false;
  }
  let schemas = components.schemas;
  if (schemas !== undefined) {
    return Object.keys(schemas).length !== 0;
  } else {
    return false;
  }
}

function getComponentSchemaNames(spec) {
  let components = spec.components;
  if (components === undefined) {
    return [];
  }
  let schemas = components.schemas;
  if (schemas !== undefined) {
    return Object.keys(schemas);
  } else {
    return [];
  }
}

function generate(spec, outputDir) {
  if (!hasComponentSchemas(spec)) {
    return Pipeline.empty;
  }
  let match = generateComponentSchemasModule(spec);
  let file_path = FileSystem.makePath(outputDir, "ComponentSchemas.res");
  let file_content = match[0];
  let file = {
    path: file_path,
    content: file_content
  };
  return Pipeline.fromFilesAndWarnings([file], match[1]);
}

export {
  extractReferences,
  generateComponentModule,
  generateComponentSchemasModule,
  hasComponentSchemas,
  getComponentSchemaNames,
  generate,
}
/* FileSystem Not a pure module */
