// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as SpecDiffer from "../core/SpecDiffer.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function formatEndpoint(endpoint) {
  let operationId = Belt_Option.getWithDefault(endpoint.operationId, "unnamed");
  return endpoint.method.toUpperCase() + ` ` + endpoint.path + ` (` + operationId + `)`;
}

function formatTags(tags) {
  if (tags !== undefined && tags.length !== 0) {
    return ` [` + tags.join(", ") + `]`;
  } else {
    return "";
  }
}

function generateAddedEndpointsSection(endpoints) {
  if (endpoints.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Added Endpoints",
    ""
  ];
  Belt_Array.forEach(endpoints, ep => {
    let tags = formatTags(ep.tags);
    let summary = Belt_Option.getWithDefault(ep.summary, "");
    let line = `- **` + formatEndpoint(ep) + `**` + tags;
    lines.push(line);
    if (summary !== "") {
      lines.push(`  ` + summary);
    }
  });
  return lines.join("\n");
}

function generateRemovedEndpointsSection(endpoints) {
  if (endpoints.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Removed Endpoints",
    ""
  ];
  Belt_Array.forEach(endpoints, ep => {
    let tags = formatTags(ep.tags);
    let line = `- **` + formatEndpoint(ep) + `**` + tags;
    lines.push(line);
  });
  return lines.join("\n");
}

function generateModifiedEndpointsSection(diffs) {
  if (diffs.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Modified Endpoints",
    ""
  ];
  Belt_Array.forEach(diffs, diff => {
    let endpoint = diff.method.toUpperCase() + ` ` + diff.path;
    let changes = [];
    if (diff.requestBodyChanged) {
      changes.push("request body");
    }
    if (diff.responseChanged) {
      changes.push("response");
    }
    let changeStr = changes.join(", ");
    let breaking = diff.breakingChange ? " **⚠️ BREAKING**" : "";
    let line = `- **` + endpoint + `**` + breaking + `: Changed ` + changeStr;
    lines.push(line);
  });
  return lines.join("\n");
}

function generateAddedSchemasSection(schemas) {
  if (schemas.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Added Schemas",
    ""
  ];
  Belt_Array.forEach(schemas, name => {
    lines.push(`- \`` + name + `\``);
  });
  return lines.join("\n");
}

function generateRemovedSchemasSection(schemas) {
  if (schemas.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Removed Schemas",
    ""
  ];
  Belt_Array.forEach(schemas, name => {
    lines.push(`- \`` + name + `\``);
  });
  return lines.join("\n");
}

function generateModifiedSchemasSection(diffs) {
  if (diffs.length === 0) {
    return "";
  }
  let lines = [
    "",
    "### Modified Schemas",
    ""
  ];
  Belt_Array.forEach(diffs, diff => {
    let breaking = diff.breakingChange ? " **⚠️ BREAKING**" : "";
    let line = `- \`` + diff.name + `\`` + breaking;
    lines.push(line);
  });
  return lines.join("\n");
}

function generateStatsSummary(diff) {
  let totalChanges = SpecDiffer.countChanges(diff);
  let hasBreaking = SpecDiffer.hasBreakingChanges(diff);
  let stats = [
    `- **Total Changes**: ` + String(totalChanges),
    `- **Added Endpoints**: ` + String(diff.addedEndpoints.length),
    `- **Removed Endpoints**: ` + String(diff.removedEndpoints.length),
    `- **Modified Endpoints**: ` + String(diff.modifiedEndpoints.length),
    `- **Added Schemas**: ` + String(diff.addedSchemas.length),
    `- **Removed Schemas**: ` + String(diff.removedSchemas.length),
    `- **Modified Schemas**: ` + String(diff.modifiedSchemas.length),
    `- **Breaking Changes**: ` + (
      hasBreaking ? "⚠️ Yes" : "✓ No"
    )
  ];
  return stats.join("\n");
}

function generateMarkdownReport(diff, baseName, forkName) {
  let sections = [
    `# API Diff Report: ` + baseName + ` → ` + forkName,
    "",
    "## Summary",
    "",
    generateStatsSummary(diff),
    generateAddedEndpointsSection(diff.addedEndpoints),
    generateRemovedEndpointsSection(diff.removedEndpoints),
    generateModifiedEndpointsSection(diff.modifiedEndpoints),
    generateAddedSchemasSection(diff.addedSchemas),
    generateRemovedSchemasSection(diff.removedSchemas),
    generateModifiedSchemasSection(diff.modifiedSchemas),
    "",
    "---",
    `*Generated on ` + new Date().toISOString() + `*`
  ];
  return Belt_Array.keep(sections, s => s !== "").join("\n");
}

function generateCompactSummary(diff) {
  let added = diff.addedEndpoints.length;
  let removed = diff.removedEndpoints.length;
  let modified = diff.modifiedEndpoints.length;
  let totalChanges = SpecDiffer.countChanges(diff);
  let breaking = SpecDiffer.hasBreakingChanges(diff) ? " (BREAKING CHANGES)" : "";
  return `Found ` + String(totalChanges) + ` changes: +` + String(added) + ` -` + String(removed) + ` ~` + String(modified) + ` endpoints` + breaking;
}

function generateMergeReport(stats, baseName, forkName) {
  let sections = [
    `# Merge Report: ` + baseName + ` + ` + forkName,
    "",
    "## Shared Code",
    "",
    `- **Shared Endpoints**: ` + String(stats.sharedEndpointCount),
    `- **Shared Schemas**: ` + String(stats.sharedSchemaCount),
    "",
    `## ` + forkName + ` Extensions`,
    "",
    `- **Extension Endpoints**: ` + String(stats.forkExtensionCount),
    `- **Extension Schemas**: ` + String(stats.forkSchemaCount),
    "",
    "## Summary",
    "",
    `The shared base contains ` + String(stats.sharedEndpointCount) + ` endpoints and ` + String(stats.sharedSchemaCount) + ` schemas that are common to both specifications.`,
    "",
    forkName + ` adds ` + String(stats.forkExtensionCount) + ` additional endpoints and ` + String(stats.forkSchemaCount) + ` schemas on top of the shared base.`,
    "",
    "---",
    `*Generated on ` + new Date().toISOString() + `*`
  ];
  return sections.join("\n");
}

function generateEndpointsByTagReport(endpoints) {
  let byTag = {};
  let untagged = [];
  Belt_Array.forEach(endpoints, ep => {
    let tags = ep.tags;
    if (tags !== undefined && tags.length !== 0) {
      return Belt_Array.forEach(tags, tag => {
        let arr = byTag[tag];
        let existing = arr !== undefined ? arr : [];
        existing.push(ep);
        byTag[tag] = existing;
      });
    } else {
      untagged.push(ep);
      return;
    }
  });
  let lines = [
    "## Endpoints by Tag",
    ""
  ];
  let tags = Belt_SortArray.stableSortBy(Object.keys(byTag), Primitive_string.compare);
  Belt_Array.forEach(tags, tag => {
    let tagEndpoints = byTag[tag];
    if (tagEndpoints === undefined) {
      return;
    }
    let count = tagEndpoints.length;
    lines.push(`### ` + tag + ` (` + String(count) + `)`);
    lines.push("");
    Belt_Array.forEach(tagEndpoints, ep => {
      lines.push(`- ` + formatEndpoint(ep));
    });
    lines.push("");
  });
  if (untagged.length !== 0) {
    lines.push(`### Untagged (` + String(untagged.length) + `)`);
    lines.push("");
    Belt_Array.forEach(untagged, ep => {
      lines.push(`- ` + formatEndpoint(ep));
    });
  }
  return lines.join("\n");
}

export {
  formatEndpoint,
  formatTags,
  generateAddedEndpointsSection,
  generateRemovedEndpointsSection,
  generateModifiedEndpointsSection,
  generateAddedSchemasSection,
  generateRemovedSchemasSection,
  generateModifiedSchemasSection,
  generateStatsSummary,
  generateMarkdownReport,
  generateCompactSummary,
  generateMergeReport,
  generateEndpointsByTagReport,
}
/* No side effect */
