// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as SchemaIRParser from "../core/SchemaIRParser.mjs";
import * as IRToSuryGenerator from "./IRToSuryGenerator.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.mjs";

function containsComponentSchemaReference(_irType) {
  while (true) {
    let irType = _irType;
    if (typeof irType !== "object") {
      return false;
    }
    switch (irType.TAG) {
      case "Array" :
        _irType = irType.items;
        continue;
      case "Object" :
        return irType.properties.some(param => containsComponentSchemaReference(param[1]));
      case "Union" :
      case "Intersection" :
        return irType._0.some(containsComponentSchemaReference);
      case "Reference" :
        return true;
      case "Option" :
        _irType = irType._0;
        continue;
      default:
        return false;
    }
  };
}

function endpointUsesComponentSchemas(endpoint) {
  let rb = endpoint.requestBody;
  let requestUsesRefs;
  if (rb !== undefined) {
    let contentTypes = Object.keys(rb.content);
    requestUsesRefs = Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Array.get(contentTypes, 0), ct => rb.content[ct]), mt => mt.schema), schema => {
      let match = SchemaIRParser.parseJsonSchema(undefined, schema);
      return containsComponentSchemaReference(match[0]);
    }), false);
  } else {
    requestUsesRefs = false;
  }
  let successCodes = [
    "200",
    "201",
    "202",
    "204"
  ];
  let responseUsesRefs = Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Array.get(Belt_Array.keepMap(successCodes, code => endpoint.responses[code]), 0), resp => resp.content), content => {
    let contentTypes = Object.keys(content);
    return Belt_Option.flatMap(Belt_Array.get(contentTypes, 0), ct => content[ct]);
  }), mt => mt.schema), schema => {
    let match = SchemaIRParser.parseJsonSchema(undefined, schema);
    return containsComponentSchemaReference(match[0]);
  }), false);
  if (requestUsesRefs) {
    return true;
  } else {
    return responseUsesRefs;
  }
}

function generateTypeAndSchemaFromJsonSchema(jsonSchema, typeName, schemaName) {
  let match = SchemaIRParser.parseJsonSchema(undefined, jsonSchema);
  let irType = match[0];
  let match$1 = IRToTypeGenerator.generateNamedType({
    name: typeName,
    description: jsonSchema.description,
    type_: irType
  }, undefined);
  let match$2 = IRToSuryGenerator.generateNamedSchema({
    name: schemaName,
    description: jsonSchema.description,
    type_: irType
  }, undefined);
  return [
    match$1[0],
    match$2[0]
  ];
}

function generateParameterExtraction(parameters) {
  if (parameters === undefined) {
    return "";
  }
  if (parameters.length === 0) {
    return "";
  }
  let lines = Belt_Array.map(parameters, param => {
    let name = param.name;
    let in_ = param.in;
    return `  // ` + in_ + ` parameter: ` + name;
  });
  return lines.join("\n");
}

function generateRequestBodyCode(requestBody, functionName) {
  if (requestBody === undefined) {
    return [
      "",
      "~body as _"
    ];
  }
  let contentTypes = Object.keys(requestBody.content);
  let firstContentType = Belt_Array.get(contentTypes, 0);
  if (firstContentType === undefined) {
    return [
      "",
      "~body as _"
    ];
  }
  let required = Belt_Option.getWithDefault(requestBody.required, false);
  let bodyParam = required ? "~body" : "~body=?";
  let schemaName = functionName + `Request`;
  let validation = required ? `  let validatedBody = ` + schemaName + `Schema->S.parseOrThrow(body)` : `  let validatedBody = body->Belt.Option.map(b => ` + schemaName + `Schema->S.parseOrThrow(b))`;
  return [
    validation,
    bodyParam
  ];
}

function generateResponseCode(responses, functionName) {
  let successCodes = [
    "200",
    "201",
    "202",
    "204"
  ];
  let successResponse = Belt_Array.get(Belt_Array.keepMap(successCodes, code => responses[code]), 0);
  if (successResponse === undefined) {
    return "  // No response schema defined\n  response";
  }
  let content = successResponse.content;
  if (content === undefined) {
    return "  response";
  }
  let contentTypes = Object.keys(content);
  let firstContentType = Belt_Array.get(contentTypes, 0);
  if (firstContentType === undefined) {
    return "  response";
  }
  let schemaName = functionName + `Response`;
  return `  let validatedResponse = ` + schemaName + `Schema->S.parseOrThrow(response)\n  validatedResponse`;
}

function generateEndpointFunction(endpoint) {
  let path = endpoint.path;
  let method = endpoint.method.toUpperCase();
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let responseTypeName = functionName + `Response`;
  let paramCode = generateParameterExtraction(endpoint.parameters);
  let match = generateRequestBodyCode(endpoint.requestBody, functionName);
  let bodyValidation = match[0];
  let responseCode = generateResponseCode(endpoint.responses, functionName);
  let hasBody = Belt_Option.isSome(endpoint.requestBody);
  let params = hasBody ? match[1] + `, ~fetch` : "~fetch";
  let summary = Belt_Option.getWithDefault(endpoint.summary, "API endpoint");
  let lines = [
    `// ` + summary,
    `let ` + functionName + ` = (` + params + `): promise<` + responseTypeName + `> => {`
  ];
  if (paramCode !== "") {
    lines.push(paramCode);
  }
  if (bodyValidation !== "") {
    lines.push(bodyValidation);
  }
  lines.push(`  `);
  lines.push(`  fetch(`);
  lines.push(`    ~url="` + path + `",`);
  lines.push(`    ~method_="` + method + `",`);
  if (hasBody) {
    lines.push(`    ~body=validatedBody,`);
  }
  lines.push(`  )->Promise.then(response => {`);
  lines.push(responseCode);
  lines.push(`->Promise.resolve`);
  lines.push(`  })`);
  lines.push(`}`);
  return lines.join("\n");
}

function generateEndpointCode(endpoint) {
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let requestTypeName = functionName + `Request`;
  let responseTypeName = functionName + `Response`;
  let requestSchemaOpt = Belt_Option.flatMap(endpoint.requestBody, rb => {
    let contentTypes = Object.keys(rb.content);
    return Belt_Option.flatMap(Belt_Array.get(contentTypes, 0), ct => Belt_Option.flatMap(rb.content[ct], mt => mt.schema));
  });
  let successCodes = [
    "200",
    "201",
    "202",
    "204"
  ];
  let responseSchemaOpt = Belt_Option.flatMap(Belt_Array.get(Belt_Array.keepMap(successCodes, code => endpoint.responses[code]), 0), resp => Belt_Option.flatMap(resp.content, content => {
    let contentTypes = Object.keys(content);
    return Belt_Option.flatMap(Belt_Array.get(contentTypes, 0), ct => Belt_Option.flatMap(content[ct], mt => mt.schema));
  }));
  let sections = [];
  if (requestSchemaOpt !== undefined) {
    let match = generateTypeAndSchemaFromJsonSchema(requestSchemaOpt, requestTypeName, functionName + `Request`);
    sections.push(match[0]);
    sections.push(match[1]);
  }
  if (responseSchemaOpt !== undefined) {
    let match$1 = generateTypeAndSchemaFromJsonSchema(responseSchemaOpt, responseTypeName, functionName + `Response`);
    sections.push(match$1[0]);
    sections.push(match$1[1]);
  } else {
    sections.push(`type ` + responseTypeName + ` = unit`);
  }
  sections.push(generateEndpointFunction(endpoint));
  return sections.join("\n\n");
}

function generateEndpointModule(endpoint) {
  let moduleName = CodegenUtils.toPascalCase(CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method));
  let header = CodegenUtils.generateFileHeader(Belt_Option.getWithDefault(endpoint.summary, `API endpoint: ` + endpoint.path));
  let needsComponentSchemas = endpointUsesComponentSchemas(endpoint);
  let lines = [
    header,
    ""
  ];
  if (needsComponentSchemas) {
    lines.push("open ComponentSchemas");
    lines.push("");
  }
  lines.push(`module ` + moduleName + ` = {`);
  lines.push(CodegenUtils.indent(generateEndpointCode(endpoint), 2));
  lines.push("}");
  return lines.join("\n");
}

function generateEndpointsModule(moduleName, endpoints, description) {
  let desc = Belt_Option.getWithDefault(description, `API endpoints for ` + moduleName);
  let header = CodegenUtils.generateFileHeader(desc);
  let needsComponentSchemas = endpoints.some(endpointUsesComponentSchemas);
  let endpointCodes = Belt_Array.map(endpoints, ep => CodegenUtils.indent(generateEndpointCode(ep), 2));
  let lines = [
    header,
    ""
  ];
  if (needsComponentSchemas) {
    lines.push("open ComponentSchemas");
    lines.push("");
  }
  lines.push(`module ` + moduleName + ` = {`);
  Belt_Array.forEach(endpointCodes, code => {
    lines.push(code);
    lines.push("");
  });
  lines.push("}");
  return lines.join("\n");
}

function generateEndpointSignature(endpoint) {
  let functionName = CodegenUtils.generateOperationName(endpoint.operationId, endpoint.path, endpoint.method);
  let responseTypeName = functionName + `Response`;
  let hasBody = Belt_Option.isSome(endpoint.requestBody);
  let params = hasBody ? "~body: 'body, ~fetch: fetchFn" : "~fetch: fetchFn";
  let summary = Belt_Option.getWithDefault(endpoint.summary, "");
  let lines = summary !== "" ? [
      `// ` + summary,
      `let ` + functionName + `: (` + params + `) => promise<` + responseTypeName + `>`
    ] : [`let ` + functionName + `: (` + params + `) => promise<` + responseTypeName + `>`];
  return lines.join("\n");
}

export {
  containsComponentSchemaReference,
  endpointUsesComponentSchemas,
  generateTypeAndSchemaFromJsonSchema,
  generateParameterExtraction,
  generateRequestBodyCode,
  generateResponseCode,
  generateEndpointFunction,
  generateEndpointCode,
  generateEndpointModule,
  generateEndpointsModule,
  generateEndpointSignature,
}
/* No side effect */
