// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SchemaIR from "../core/SchemaIR.mjs";
import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as IRToSuryGenerator from "./IRToSuryGenerator.mjs";
import * as ReferenceResolver from "../core/ReferenceResolver.mjs";

function addWarning(ctx, warning) {
  ctx.warnings.push(warning);
}

function generateTypeWithContext(ctx, _depthOpt, _irType) {
  while (true) {
    let depthOpt = _depthOpt;
    let irType = _irType;
    let depth = depthOpt !== undefined ? depthOpt : 0;
    if (depth > 20) {
      addWarning(ctx, {
        TAG: "DepthLimitReached",
        depth: depth,
        path: ctx.path
      });
      return "JSON.t";
    }
    if (typeof irType !== "object") {
      switch (irType) {
        case "Boolean" :
          return "bool";
        case "Null" :
          return "unit";
        case "Unknown" :
          return "JSON.t";
      }
    } else {
      switch (irType.TAG) {
        case "String" :
          return "string";
        case "Number" :
          return "float";
        case "Integer" :
          return "int";
        case "Array" :
          let items = irType.items;
          let itemType = generateTypeWithContext(ctx, depth + 1 | 0, items);
          let itemTypeStr;
          if (typeof items !== "object" || items.TAG !== "Object" || items.properties.length === 0) {
            itemTypeStr = itemType;
          } else {
            addWarning(ctx, {
              TAG: "FallbackToJson",
              reason: "Inline objects in arrays not supported in ReScript",
              context: {
                path: ctx.path,
                operation: "generating array item type",
                schema: undefined
              }
            });
            itemTypeStr = "JSON.t";
          }
          return `array<` + itemTypeStr + `>`;
        case "Object" :
          let additionalProperties = irType.additionalProperties;
          let properties = irType.properties;
          if (depth > 0 && properties.length !== 0) {
            addWarning(ctx, {
              TAG: "FallbackToJson",
              reason: "Nested objects use JSON.t to avoid ReScript syntax limitations",
              context: {
                path: ctx.path,
                operation: "generating nested object type",
                schema: undefined
              }
            });
            return "JSON.t";
          }
          if (properties.length === 0) {
            if (additionalProperties === undefined) {
              return "JSON.t";
            }
            let valueTypeStr = generateTypeWithContext(ctx, depth + 1 | 0, additionalProperties);
            return `dict<` + valueTypeStr + `>`;
          }
          let fields = properties.map(param => {
            let name = param[0];
            let fieldType = generateTypeWithContext(ctx, depth + 1 | 0, param[1]);
            let finalFieldType = param[2] ? fieldType : `option<` + fieldType + `>`;
            let fieldName = CodegenUtils.toCamelCase(name);
            let escapedFieldName = CodegenUtils.escapeKeyword(fieldName);
            let asAnnotation = escapedFieldName !== fieldName ? `@as("` + name + `") ` : "";
            return `  ` + asAnnotation + escapedFieldName + `: ` + finalFieldType + `,`;
          });
          let fieldsStr = fields.join("\n");
          return `{\n` + fieldsStr + `\n}`;
        case "Literal" :
          let tmp = irType._0;
          if (typeof tmp !== "object") {
            return "unit";
          }
          switch (tmp.TAG) {
            case "StringLiteral" :
              return "string";
            case "NumberLiteral" :
              return "float";
            case "BooleanLiteral" :
              return "bool";
          }
        case "Union" :
          let types = irType._0;
          let match = Stdlib_Array.reduce(types, [
            false,
            false,
            undefined,
            undefined
          ], (param, t) => {
            let arrType = param[2];
            let hasArr = param[0];
            if (typeof t !== "object" || t.TAG !== "Array") {
              return [
                hasArr,
                true,
                arrType,
                t
              ];
            } else {
              return [
                true,
                param[1],
                t.items,
                param[3]
              ];
            }
          });
          let nonArrayType = match[3];
          let arrayItemType = match[2];
          let isSingleItemArrayUnion = arrayItemType !== undefined && nonArrayType !== undefined ? match[0] && match[1] && SchemaIR.equals(arrayItemType, nonArrayType) : false;
          if (isSingleItemArrayUnion) {
            let itemTypeStr$1 = arrayItemType !== undefined ? generateTypeWithContext(ctx, depth + 1 | 0, arrayItemType) : "JSON.t";
            return `array<` + itemTypeStr$1 + `>`;
          }
          let allStringLiterals = types.every(t => {
            if (typeof t !== "object") {
              return false;
            }
            if (t.TAG !== "Literal") {
              return false;
            }
            let tmp = t._0;
            if (typeof tmp !== "object") {
              return false;
            } else {
              return tmp.TAG === "StringLiteral";
            }
          });
          if (allStringLiterals && types.length !== 0 && types.length <= 20) {
            let variants = types.map(t => {
              if (typeof t !== "object") {
                return "#Unknown";
              }
              if (t.TAG !== "Literal") {
                return "#Unknown";
              }
              let str = t._0;
              if (typeof str !== "object") {
                return "#Unknown";
              }
              if (str.TAG !== "StringLiteral") {
                return "#Unknown";
              }
              let variantName = CodegenUtils.toPascalCase(str._0);
              return `#` + variantName;
            });
            return `[` + variants.join(" | ") + `]`;
          }
          let typeNames = types.map(SchemaIR.toString).join(" | ");
          addWarning(ctx, {
            TAG: "ComplexUnionSimplified",
            location: ctx.path,
            types: typeNames
          });
          return "JSON.t";
        case "Intersection" :
          addWarning(ctx, {
            TAG: "IntersectionNotFullySupported",
            location: ctx.path,
            note: "Using first type only, consider implementing object merging"
          });
          let firstType = irType._0[0];
          if (firstType === undefined) {
            return "JSON.t";
          }
          _irType = firstType;
          _depthOpt = depth + 1 | 0;
          continue;
        case "Reference" :
          let ref = irType._0;
          let typePath = ReferenceResolver.refToTypePath(ctx.insideComponentSchemas, ref);
          if (typePath !== undefined) {
            return typePath;
          } else {
            addWarning(ctx, {
              TAG: "FallbackToJson",
              reason: `Could not resolve reference: ` + ref,
              context: {
                path: ctx.path,
                operation: "generating reference type",
                schema: undefined
              }
            });
            return "JSON.t";
          }
        case "Option" :
          let innerTypeStr = generateTypeWithContext(ctx, depth + 1 | 0, irType._0);
          return `option<` + innerTypeStr + `>`;
      }
    }
  };
}

function generateType(depthOpt, pathOpt, insideComponentSchemasOpt, irType) {
  let depth = depthOpt !== undefined ? depthOpt : 0;
  let path = pathOpt !== undefined ? pathOpt : "";
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let ctx = {
    warnings: [],
    path: path,
    insideComponentSchemas: insideComponentSchemas
  };
  let typeStr = generateTypeWithContext(ctx, depth, irType);
  return [
    typeStr,
    ctx.warnings
  ];
}

function generateNamedType(namedSchema, insideComponentSchemasOpt) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let ctx = {
    warnings: [],
    path: `type.` + namedSchema.name,
    insideComponentSchemas: insideComponentSchemas
  };
  let typeCode = generateTypeWithContext(ctx, 0, namedSchema.type_);
  let typeName = namedSchema.name;
  let desc = namedSchema.description;
  let doc = desc !== undefined ? CodegenUtils.generateDocComment(undefined, desc, undefined) : "";
  return [
    doc + `type ` + typeName + ` = ` + typeCode,
    ctx.warnings
  ];
}

function generateAllTypes(context) {
  let allWarnings = [];
  let types = Belt_SortArray.stableSortBy(Object.values(context.schemas), (a, b) => Primitive_string.compare(a.name, b.name)).map(namedSchema => {
    let match = generateNamedType(namedSchema, undefined);
    allWarnings.push(...match[1]);
    return match[0];
  });
  return [
    types,
    allWarnings
  ];
}

function generateTypeAndSchema(namedSchema) {
  let match = generateNamedType(namedSchema, undefined);
  let match$1 = IRToSuryGenerator.generateNamedSchema(namedSchema, undefined);
  let allWarnings = match[1].concat(match$1[1]);
  return [
    [
      match[0],
      match$1[0]
    ],
    allWarnings
  ];
}

export {
  addWarning,
  generateTypeWithContext,
  generateType,
  generateNamedType,
  generateAllTypes,
  generateTypeAndSchema,
}
/* No side effect */
