// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SchemaIR from "../core/SchemaIR.mjs";
import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as ReferenceResolver from "../core/ReferenceResolver.mjs";

function addWarning(ctx, warning) {
  ctx.warnings.push(warning);
}

function generateSchemaWithContext(ctx, _depthOpt, _irType) {
  while (true) {
    let depthOpt = _depthOpt;
    let irType = _irType;
    let depth = depthOpt !== undefined ? depthOpt : 0;
    if (typeof irType !== "object") {
      switch (irType) {
        case "Boolean" :
          return "S.bool";
        case "Null" :
          return "S.null";
        case "Unknown" :
          return "S.json";
      }
    } else {
      switch (irType.TAG) {
        case "String" :
          let constraints = irType.constraints;
          let base = "S.string";
          let withMin = Stdlib_Option.mapOr(constraints.minLength, base, min => base + `->S.min(` + min.toString() + `)`);
          let withMax = Stdlib_Option.mapOr(constraints.maxLength, withMin, max => withMin + `->S.max(` + max.toString() + `)`);
          return Stdlib_Option.mapOr(constraints.pattern, withMax, pattern => withMax + `->S.pattern(%re("/` + CodegenUtils.escapeString(pattern) + `/"))`);
        case "Number" :
          let constraints$1 = irType.constraints;
          let base$1 = "S.float";
          let withMin$1 = Stdlib_Option.mapOr(constraints$1.minimum, base$1, min => base$1 + `->S.min(` + (min | 0).toString() + `)`);
          return Stdlib_Option.mapOr(constraints$1.maximum, withMin$1, max => withMin$1 + `->S.max(` + (max | 0).toString() + `)`);
        case "Integer" :
          let constraints$2 = irType.constraints;
          let base$2 = "S.int";
          let withMin$2 = Stdlib_Option.mapOr(constraints$2.minimum, base$2, min => base$2 + `->S.min(` + (min | 0).toString() + `)`);
          return Stdlib_Option.mapOr(constraints$2.maximum, withMin$2, max => withMin$2 + `->S.max(` + (max | 0).toString() + `)`);
        case "Array" :
          let constraints$3 = irType.constraints;
          let itemsSchema = generateSchemaWithContext(ctx, depth + 1 | 0, irType.items);
          let base$3 = `S.array(` + itemsSchema + `)`;
          let withMin$3 = Stdlib_Option.mapOr(constraints$3.minItems, base$3, min => base$3 + `->S.min(` + min.toString() + `)`);
          return Stdlib_Option.mapOr(constraints$3.maxItems, withMin$3, max => withMin$3 + `->S.max(` + max.toString() + `)`);
        case "Object" :
          let additionalProperties = irType.additionalProperties;
          let properties = irType.properties;
          if (depth > 0) {
            addWarning(ctx, {
              TAG: "FallbackToJson",
              reason: "Nested objects use S.json to avoid ReScript syntax limitations",
              context: {
                path: ctx.path,
                operation: "generating nested object schema",
                schema: undefined
              }
            });
            return "S.json";
          }
          if (properties.length === 0) {
            if (additionalProperties === undefined) {
              return "S.json";
            }
            let valueSchema = generateSchemaWithContext(ctx, depth + 1 | 0, additionalProperties);
            return `S.dict(` + valueSchema + `)`;
          }
          let fields = properties.map(param => {
            let name = param[0];
            let fieldSchema = generateSchemaWithContext(ctx, depth + 1 | 0, param[1]);
            let fieldName = CodegenUtils.escapeKeyword(CodegenUtils.toCamelCase(name));
            if (param[2]) {
              return `    ` + fieldName + `: s.field("` + name + `", ` + fieldSchema + `),`;
            } else {
              return `    ` + fieldName + `: s.fieldOr("` + name + `", S.nullableAsOption(` + fieldSchema + `), None),`;
            }
          });
          let fieldsStr = fields.join("\n");
          return `S.object(s => {\n` + fieldsStr + `\n  })`;
        case "Literal" :
          let literalValue = irType._0;
          if (typeof literalValue !== "object") {
            return `S.literal(null)`;
          }
          switch (literalValue.TAG) {
            case "StringLiteral" :
              return `S.literal("` + CodegenUtils.escapeString(literalValue._0) + `")`;
            case "NumberLiteral" :
              return `S.literal(` + literalValue._0.toString() + `)`;
            case "BooleanLiteral" :
              if (literalValue._0) {
                return `S.literal(true)`;
              } else {
                return `S.literal(false)`;
              }
          }
        case "Union" :
          let types = irType._0;
          let match = Stdlib_Array.reduce(types, [
            false,
            false,
            undefined,
            undefined
          ], (param, t) => {
            let arrType = param[2];
            let hasArr = param[0];
            if (typeof t !== "object" || t.TAG !== "Array") {
              return [
                hasArr,
                true,
                arrType,
                t
              ];
            } else {
              return [
                true,
                param[1],
                t.items,
                param[3]
              ];
            }
          });
          let nonArrayType = match[3];
          let arrayItemType = match[2];
          let hasNonArrays = match[1];
          let hasArrays = match[0];
          let isSingleItemArrayUnion = arrayItemType !== undefined && nonArrayType !== undefined ? hasArrays && hasNonArrays && SchemaIR.equals(arrayItemType, nonArrayType) : false;
          if (isSingleItemArrayUnion) {
            let itemSchema = arrayItemType !== undefined ? generateSchemaWithContext(ctx, depth + 1 | 0, arrayItemType) : "S.json";
            return `S.array(` + itemSchema + `)`;
          }
          if (hasArrays && hasNonArrays) {
            let typeNames = types.map(SchemaIR.toString).join(" | ");
            addWarning(ctx, {
              TAG: "ComplexUnionSimplified",
              location: ctx.path,
              types: typeNames
            });
            return "S.json";
          }
          let allStringLiterals = types.every(t => {
            if (typeof t !== "object") {
              return false;
            }
            if (t.TAG !== "Literal") {
              return false;
            }
            let tmp = t._0;
            if (typeof tmp !== "object") {
              return false;
            } else {
              return tmp.TAG === "StringLiteral";
            }
          });
          if (allStringLiterals && types.length !== 0 && types.length <= 20) {
            let variants = types.map(t => generateSchemaWithContext(ctx, depth + 1 | 0, t)).join(", ");
            return `S.union([` + variants + `])`;
          }
          let typeNames$1 = types.map(SchemaIR.toString).join(" | ");
          addWarning(ctx, {
            TAG: "ComplexUnionSimplified",
            location: ctx.path,
            types: typeNames$1
          });
          return "S.json";
        case "Intersection" :
          addWarning(ctx, {
            TAG: "IntersectionNotFullySupported",
            location: ctx.path,
            note: "Using first type only for schema generation"
          });
          let firstType = irType._0[0];
          if (firstType === undefined) {
            return "S.unknown";
          }
          _irType = firstType;
          _depthOpt = depth + 1 | 0;
          continue;
        case "Reference" :
          let ref = irType._0;
          let schemaPath = ReferenceResolver.refToSchemaPath(ctx.insideComponentSchemas, ref);
          if (schemaPath !== undefined) {
            return schemaPath;
          } else {
            addWarning(ctx, {
              TAG: "FallbackToJson",
              reason: `Could not resolve reference: ` + ref,
              context: {
                path: ctx.path,
                operation: "generating reference schema",
                schema: undefined
              }
            });
            return "S.json";
          }
        case "Option" :
          let innerSchema = generateSchemaWithContext(ctx, depth + 1 | 0, irType._0);
          return `S.nullableAsOption(` + innerSchema + `)`;
      }
    }
  };
}

function generateSchema(depthOpt, pathOpt, insideComponentSchemasOpt, irType) {
  let depth = depthOpt !== undefined ? depthOpt : 0;
  let path = pathOpt !== undefined ? pathOpt : "";
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let ctx = {
    warnings: [],
    path: path,
    insideComponentSchemas: insideComponentSchemas
  };
  let schemaStr = generateSchemaWithContext(ctx, depth, irType);
  return [
    schemaStr,
    ctx.warnings
  ];
}

function generateNamedSchema(namedSchema, insideComponentSchemasOpt) {
  let insideComponentSchemas = insideComponentSchemasOpt !== undefined ? insideComponentSchemasOpt : false;
  let ctx = {
    warnings: [],
    path: `schema.` + namedSchema.name,
    insideComponentSchemas: insideComponentSchemas
  };
  let schemaCode = generateSchemaWithContext(ctx, 0, namedSchema.type_);
  let schemaName = namedSchema.name + `Schema`;
  let desc = namedSchema.description;
  let doc = desc !== undefined ? CodegenUtils.generateDocComment(undefined, desc, undefined) : "";
  return [
    doc + `let ` + schemaName + ` = ` + schemaCode,
    ctx.warnings
  ];
}

function generateAllSchemas(context) {
  let allWarnings = [];
  let schemas = Belt_SortArray.stableSortBy(Object.values(context.schemas), (a, b) => Primitive_string.compare(a.name, b.name)).map(namedSchema => {
    let match = generateNamedSchema(namedSchema, undefined);
    allWarnings.push(...match[1]);
    return match[0];
  });
  return [
    schemas,
    allWarnings
  ];
}

export {
  addWarning,
  generateSchemaWithContext,
  generateSchema,
  generateNamedSchema,
  generateAllSchemas,
}
/* No side effect */
