// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "../core/Pipeline.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as FileSystem from "../core/FileSystem.mjs";
import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as OpenAPIParser from "../core/OpenAPIParser.mjs";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as SchemaIRParser from "../core/SchemaIRParser.mjs";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as EndpointGenerator from "./EndpointGenerator.mjs";
import * as IRToSuryGenerator from "./IRToSuryGenerator.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.mjs";

function generateTagModule(tag, endpoints, includeSchemasOpt) {
  let includeSchemas = includeSchemasOpt !== undefined ? includeSchemasOpt : true;
  let moduleName = CodegenUtils.toPascalCase(tag);
  let description = `API endpoints for ` + tag;
  let header = CodegenUtils.generateFileHeader(description);
  let lines = [
    header,
    "",
    `module ` + moduleName + ` = {`
  ];
  if (includeSchemas) {
    Belt_Array.forEachWithIndex(endpoints, (_idx, ep) => {
      let rb = ep.requestBody;
      if (rb !== undefined) {
        let contentTypes = Object.keys(rb.content);
        Belt_Array.forEach(contentTypes, ct => {
          
        });
      }
      let responseCodes = Object.keys(ep.responses);
      Belt_Array.forEach(responseCodes, code => {
        let resp = ep.responses[code];
        if (resp === undefined) {
          return;
        }
        let content = resp.content;
        if (content === undefined) {
          return;
        }
        let contentTypes = Object.keys(content);
        Belt_Array.forEach(contentTypes, ct => {
          
        });
      });
    });
  }
  Belt_Array.forEachWithIndex(endpoints, (_idx, ep) => {
    let endpointCode = EndpointGenerator.generateEndpointCode(ep);
    let indented = CodegenUtils.indent(endpointCode, 2);
    lines.push(indented);
    lines.push("");
  });
  lines.push("}");
  return lines.join("\n");
}

function generateAllTagModules(endpoints, includeSchemasOpt) {
  let includeSchemas = includeSchemasOpt !== undefined ? includeSchemasOpt : true;
  let grouped = OpenAPIParser.groupByTag(endpoints);
  let tags = Belt_SortArray.stableSortBy(Object.keys(grouped), Primitive_string.compare);
  return Belt_Array.map(tags, tag => {
    let tagEndpoints = grouped[tag];
    if (tagEndpoints === undefined) {
      return [
        tag,
        ""
      ];
    }
    let moduleCode = generateTagModule(tag, tagEndpoints, includeSchemas);
    return [
      tag,
      moduleCode
    ];
  });
}

function generateIndexModule(tags, moduleNameOpt) {
  let moduleName = moduleNameOpt !== undefined ? moduleNameOpt : "API";
  let header = CodegenUtils.generateFileHeader(`Main API module - re-exports all endpoint modules`);
  let lines = [
    header,
    "",
    `module ` + moduleName + ` = {`
  ];
  Belt_Array.forEach(tags, tag => {
    let tagModule = CodegenUtils.toPascalCase(tag);
    lines.push(`  module ` + tagModule + ` = ` + tagModule);
  });
  lines.push("}");
  return lines.join("\n");
}

function generateFlatModule(moduleName, endpoints) {
  let description = `All API endpoints in ` + moduleName;
  let header = CodegenUtils.generateFileHeader(description);
  let lines = [
    header,
    "",
    `module ` + moduleName + ` = {`
  ];
  Belt_Array.forEach(endpoints, ep => {
    let endpointCode = EndpointGenerator.generateEndpointCode(ep);
    let indented = CodegenUtils.indent(endpointCode, 2);
    lines.push(indented);
    lines.push("");
  });
  lines.push("}");
  return lines.join("\n");
}

function generateSharedModule(endpoints, schemas) {
  let header = CodegenUtils.generateFileHeader("Shared API code - common to all forks");
  let lines = [
    header,
    "",
    "module Shared = {"
  ];
  if (schemas !== undefined) {
    let schemaNames = Belt_SortArray.stableSortBy(Object.keys(schemas), Primitive_string.compare);
    lines.push("  // Component Schemas");
    lines.push("");
    Belt_Array.forEach(schemaNames, name => {
      let schema = schemas[name];
      if (schema === undefined) {
        return;
      }
      let match = SchemaIRParser.parseJsonSchema(undefined, schema);
      let irType = match[0];
      let match$1 = IRToTypeGenerator.generateNamedType({
        name: name,
        description: schema.description,
        type_: irType
      }, undefined);
      let match$2 = IRToSuryGenerator.generateNamedSchema({
        name: name + `Schema`,
        description: schema.description,
        type_: irType
      }, undefined);
      lines.push(CodegenUtils.indent(match$1[0], 2));
      lines.push(CodegenUtils.indent(match$2[0], 2));
      lines.push("");
    });
  }
  let grouped = OpenAPIParser.groupByTag(endpoints);
  let tags = Belt_SortArray.stableSortBy(Object.keys(grouped), Primitive_string.compare);
  Belt_Array.forEach(tags, tag => {
    let tagEndpoints = grouped[tag];
    if (tagEndpoints === undefined) {
      return;
    }
    let tagModule = CodegenUtils.toPascalCase(tag);
    lines.push(`  module ` + tagModule + ` = {`);
    Belt_Array.forEach(tagEndpoints, ep => {
      let endpointCode = EndpointGenerator.generateEndpointCode(ep);
      let indented = CodegenUtils.indent(endpointCode, 4);
      lines.push(indented);
      lines.push("");
    });
    lines.push("  }");
    lines.push("");
  });
  lines.push("}");
  return lines.join("\n");
}

function generateExtensionModule(forkName, endpoints, schemas) {
  let moduleName = CodegenUtils.toPascalCase(forkName) + `Extensions`;
  let header = CodegenUtils.generateFileHeader(forkName + ` specific extensions - additional endpoints and schemas`);
  let lines = [
    header,
    "",
    `module ` + moduleName + ` = {`
  ];
  if (schemas !== undefined) {
    let schemaNames = Object.keys(schemas);
    if (schemaNames.length !== 0) {
      lines.push("  // Extension Schemas");
      lines.push("");
      let sorted = Belt_SortArray.stableSortBy(schemaNames, Primitive_string.compare);
      Belt_Array.forEach(sorted, name => {
        let schema = schemas[name];
        if (schema === undefined) {
          return;
        }
        let match = SchemaIRParser.parseJsonSchema(undefined, schema);
        let irType = match[0];
        let match$1 = IRToTypeGenerator.generateNamedType({
          name: name,
          description: schema.description,
          type_: irType
        }, undefined);
        let match$2 = IRToSuryGenerator.generateNamedSchema({
          name: name + `Schema`,
          description: schema.description,
          type_: irType
        }, undefined);
        lines.push(CodegenUtils.indent(match$1[0], 2));
        lines.push(CodegenUtils.indent(match$2[0], 2));
        lines.push("");
      });
    }
  }
  if (endpoints.length !== 0) {
    lines.push("  // Extension Endpoints");
    lines.push("");
    let grouped = OpenAPIParser.groupByTag(endpoints);
    let tags = Belt_SortArray.stableSortBy(Object.keys(grouped), Primitive_string.compare);
    Belt_Array.forEach(tags, tag => {
      let tagEndpoints = grouped[tag];
      if (tagEndpoints === undefined) {
        return;
      }
      let tagModule = CodegenUtils.toPascalCase(tag);
      lines.push(`  module ` + tagModule + ` = {`);
      Belt_Array.forEach(tagEndpoints, ep => {
        let endpointCode = EndpointGenerator.generateEndpointCode(ep);
        let indented = CodegenUtils.indent(endpointCode, 4);
        lines.push(indented);
        lines.push("");
      });
      lines.push("  }");
      lines.push("");
    });
  }
  lines.push("}");
  return lines.join("\n");
}

function generateCombinedModule(forkName, sharedEndpoints, extensionEndpoints, sharedSchemas, extensionSchemas) {
  let sharedModule = generateSharedModule(sharedEndpoints, sharedSchemas);
  let extensionModule = generateExtensionModule(forkName, extensionEndpoints, extensionSchemas);
  return [
    sharedModule,
    "",
    extensionModule
  ].join("\n");
}

function generateTagModules(endpoints, outputDir) {
  let tagModules = generateAllTagModules(endpoints, true);
  let files = tagModules.map(param => {
    let filename = CodegenUtils.toPascalCase(param[0]) + `.res`;
    return {
      path: FileSystem.makePath(outputDir, filename),
      content: param[1]
    };
  });
  return Pipeline.fromFilesAndWarnings(files, []);
}

function generateFlat(moduleName, endpoints, outputDir) {
  let code = generateFlatModule(moduleName, endpoints);
  return Pipeline.fromFile({
    path: FileSystem.makePath(outputDir, moduleName + `.res`),
    content: code
  });
}

export {
  generateTagModule,
  generateAllTagModules,
  generateIndexModule,
  generateFlatModule,
  generateSharedModule,
  generateExtensionModule,
  generateCombinedModule,
  generateTagModules,
  generateFlat,
}
/* FileSystem Not a pure module */
