// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CodegenUtils from "../core/CodegenUtils.mjs";
import * as OpenAPIParser from "../core/OpenAPIParser.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SchemaIRParser from "../core/SchemaIRParser.mjs";
import * as IRToSuryGenerator from "./IRToSuryGenerator.mjs";
import * as IRToTypeGenerator from "./IRToTypeGenerator.mjs";

function generateTypeAndSchema(name, schema) {
  let match = SchemaIRParser.parseJsonSchema(undefined, schema);
  let irType = match[0];
  let match$1 = IRToTypeGenerator.generateNamedType({
    name: name,
    description: schema.description,
    type_: irType
  }, undefined);
  let match$2 = IRToSuryGenerator.generateNamedSchema({
    name: name + `Schema`,
    description: schema.description,
    type_: irType
  }, undefined);
  return match$1[0] + `\n\n` + match$2[0];
}

function generateComponentSchemas(components) {
  let schemas = Stdlib_Option.flatMap(components, c => c.schemas);
  if (schemas === undefined) {
    return "// No component schemas defined\n";
  }
  let schemaCode = Object.entries(schemas).map(param => generateTypeAndSchema(param[0], param[1])).join("\n\n");
  return `// Component Schemas\n\n` + schemaCode;
}

function generateOperationSchemas(operationId, operation) {
  let parts = [];
  let requestSchemaOpt = Stdlib_Option.flatMap(operation.requestBody, body => Stdlib_Option.flatMap(body.content["application/json"], media => media.schema));
  if (requestSchemaOpt !== undefined) {
    let requestName = CodegenUtils.toPascalCase(operationId) + `Request`;
    let match = SchemaIRParser.parseJsonSchema(undefined, requestSchemaOpt);
    let irType = match[0];
    let match$1 = IRToTypeGenerator.generateNamedType({
      name: requestName,
      description: requestSchemaOpt.description,
      type_: irType
    }, undefined);
    let match$2 = IRToSuryGenerator.generateNamedSchema({
      name: requestName + `Schema`,
      description: requestSchemaOpt.description,
      type_: irType
    }, undefined);
    parts.push(match$1[0]);
    parts.push(match$2[0]);
  }
  let response200 = operation.responses["200"];
  let response201 = operation.responses["201"];
  let response = Stdlib_Option.orElse(response200, response201);
  let responseSchemaOpt = Stdlib_Option.flatMap(response, resp => Stdlib_Option.flatMap(Stdlib_Option.flatMap(resp.content, content => content["application/json"]), media => media.schema));
  if (responseSchemaOpt !== undefined) {
    let responseName = CodegenUtils.toPascalCase(operationId) + `Response`;
    let match$3 = SchemaIRParser.parseJsonSchema(undefined, responseSchemaOpt);
    let irType$1 = match$3[0];
    let match$4 = IRToTypeGenerator.generateNamedType({
      name: responseName,
      description: responseSchemaOpt.description,
      type_: irType$1
    }, undefined);
    let match$5 = IRToSuryGenerator.generateNamedSchema({
      name: responseName + `Schema`,
      description: responseSchemaOpt.description,
      type_: irType$1
    }, undefined);
    parts.push(match$4[0]);
    parts.push(match$5[0]);
  }
  return parts.join("\n\n");
}

function generateEndpointModule(path, method, operation) {
  let operationId = OpenAPIParser.getOperationId(path, method, operation);
  let moduleName = CodegenUtils.toPascalCase(operationId);
  let doc = CodegenUtils.generateDocComment(operation.summary, operation.description, undefined);
  let schemas = generateOperationSchemas(operationId, operation);
  let methodStr = method === "GET" ? "GET" : (
      method === "PUT" ? "PUT" : (
          method === "DELETE" ? "DELETE" : (
              method === "HEAD" ? "HEAD" : (
                  method === "POST" ? "POST" : (
                      method === "PATCH" ? "PATCH" : "OPTIONS"
                    )
                )
            )
        )
    );
  let endpointInfo = `  let endpoint = "` + path + `"\n  let method = #` + methodStr;
  return doc + `module ` + moduleName + ` = {\n` + CodegenUtils.indent(schemas, 1) + `\n\n` + endpointInfo + `\n}`;
}

export {
  generateTypeAndSchema,
  generateComponentSchemas,
  generateOperationSchemas,
  generateEndpointModule,
}
/* No side effect */
