// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pipeline from "./core/Pipeline.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as FileSystem from "./core/FileSystem.mjs";
import * as SpecDiffer from "./core/SpecDiffer.mjs";
import * as SpecMerger from "./core/SpecMerger.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as CodegenUtils from "./core/CodegenUtils.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as OpenAPIParser from "./core/OpenAPIParser.mjs";
import * as ModuleGenerator from "./generators/ModuleGenerator.mjs";
import * as SchemaRefResolver from "./core/SchemaRefResolver.mjs";
import * as DiffReportGenerator from "./generators/DiffReportGenerator.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as ComponentSchemaGenerator from "./generators/ComponentSchemaGenerator.mjs";

function generateSingleSpecPure(spec, config) {
  try {
    let componentOutput = ComponentSchemaGenerator.generate(spec, config.outputDir);
    let allEndpoints = OpenAPIParser.getAllEndpoints(spec);
    let includeTags = config.includeTags;
    let endpoints;
    if (includeTags !== undefined) {
      let excludeTags = Belt_Option.getWithDefault(config.excludeTags, []);
      endpoints = OpenAPIParser.filterByTags(allEndpoints, includeTags, excludeTags);
    } else {
      endpoints = allEndpoints;
    }
    let endpointOutput = config.modulePerTag ? ModuleGenerator.generateTagModules(endpoints, config.outputDir) : ModuleGenerator.generateFlat("API", endpoints, config.outputDir);
    let combined = Pipeline.combine([
      componentOutput,
      endpointOutput
    ]);
    return {
      TAG: "Ok",
      _0: combined
    };
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "UnknownError",
          message: "Unknown error",
          context: undefined
        }
      };
    }
    let message = Belt_Option.getWithDefault(Stdlib_JsExn.message(err._1), "Unknown error");
    return {
      TAG: "Error",
      _0: {
        TAG: "UnknownError",
        message: message,
        context: undefined
      }
    };
  }
}

async function generateSingleSpec(spec, config) {
  let err = generateSingleSpecPure(spec, config);
  if (err.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
  let output = err._0;
  let errors = FileSystem.writeFiles(output.files);
  if (errors.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        generatedFiles: errors._0,
        diff: undefined,
        warnings: output.warnings
      }
    };
  }
  let message = `Failed to write files: ` + errors._0.join(", ");
  return {
    TAG: "Error",
    _0: {
      TAG: "UnknownError",
      message: message,
      context: undefined
    }
  };
}

function processForkPure(baseSpec, baseEndpoints, fork, config) {
  try {
    let forkEndpoints = OpenAPIParser.getAllEndpoints(fork.spec);
    let diff = SpecDiffer.generateDiff(baseSpec, fork.spec, baseEndpoints, forkEndpoints);
    let diffReportFile;
    if (config.generateDiffReport) {
      let report = DiffReportGenerator.generateMarkdownReport(diff, "base", fork.name);
      let reportPath = FileSystem.makePath(config.outputDir, fork.name + `-diff.md`);
      diffReportFile = {
        path: reportPath,
        content: report
      };
    } else {
      diffReportFile = undefined;
    }
    let match = SpecMerger.mergeSpecs(baseSpec, fork.spec, baseEndpoints, forkEndpoints, config.strategy);
    let extensionsSpec = match[1];
    let sharedSpec = match[0];
    let sharedEndpoints = OpenAPIParser.getAllEndpoints(sharedSpec);
    let extensionEndpoints = OpenAPIParser.getAllEndpoints(extensionsSpec);
    let sharedSchemas = Belt_Option.flatMap(sharedSpec.components, c => c.schemas);
    let extensionSchemas = Belt_Option.flatMap(extensionsSpec.components, c => c.schemas);
    let mergeStats = SpecMerger.getMergeStats(baseEndpoints, forkEndpoints, Belt_Option.flatMap(baseSpec.components, c => c.schemas), Belt_Option.flatMap(fork.spec.components, c => c.schemas));
    let mergeReport = DiffReportGenerator.generateMergeReport(mergeStats, "base", fork.name);
    let mergeReportPath = FileSystem.makePath(config.outputDir, fork.name + `-merge.md`);
    let mergeReportFile = {
      path: mergeReportPath,
      content: mergeReport
    };
    let match$1 = config.strategy;
    let codeFile;
    let exit = 0;
    switch (match$1) {
      case "Separate" :
        let code = ModuleGenerator.generateFlatModule(CodegenUtils.toPascalCase(fork.name), forkEndpoints);
        let outputPath = FileSystem.makePath(config.outputDir, fork.name + `.res`);
        codeFile = {
          path: outputPath,
          content: code
        };
        break;
      case "SharedBase" :
      case "ConditionalCompilation" :
        exit = 1;
        break;
    }
    if (exit === 1) {
      let code$1 = ModuleGenerator.generateCombinedModule(fork.name, sharedEndpoints, extensionEndpoints, sharedSchemas, extensionSchemas);
      let outputPath$1 = FileSystem.makePath(config.outputDir, fork.name + `.res`);
      codeFile = {
        path: outputPath$1,
        content: code$1
      };
    }
    let files = diffReportFile !== undefined ? [
        diffReportFile,
        mergeReportFile,
        codeFile
      ] : [
        mergeReportFile,
        codeFile
      ];
    return {
      TAG: "Ok",
      _0: Pipeline.fromFilesAndWarnings(files, [])
    };
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "UnknownError",
          message: "Unknown error",
          context: undefined
        }
      };
    }
    let message = Belt_Option.getWithDefault(Stdlib_JsExn.message(err._1), "Unknown error");
    return {
      TAG: "Error",
      _0: {
        TAG: "UnknownError",
        message: message,
        context: undefined
      }
    };
  }
}

function generateMultiSpecPure(baseSpec, forkSpecs, config) {
  try {
    let baseEndpoints = OpenAPIParser.getAllEndpoints(baseSpec);
    let forkResults = Belt_Array.map(forkSpecs, fork => processForkPure(baseSpec, baseEndpoints, fork, config));
    let errors = Belt_Array.keepMap(forkResults, result => {
      if (result.TAG === "Ok") {
        return;
      } else {
        return result._0;
      }
    });
    if (errors.length !== 0) {
      return {
        TAG: "Error",
        _0: Belt_Array.getExn(errors, 0)
      };
    }
    let outputs = Belt_Array.keepMap(forkResults, result => {
      if (result.TAG === "Ok") {
        return result._0;
      }
    });
    return {
      TAG: "Ok",
      _0: Pipeline.combine(outputs)
    };
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID !== "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "UnknownError",
          message: "Unknown error",
          context: undefined
        }
      };
    }
    let message = Belt_Option.getWithDefault(Stdlib_JsExn.message(err._1), "Unknown error");
    return {
      TAG: "Error",
      _0: {
        TAG: "UnknownError",
        message: message,
        context: undefined
      }
    };
  }
}

async function generateMultiSpec(baseSpec, forkSpecs, config) {
  let err = generateMultiSpecPure(baseSpec, forkSpecs, config);
  if (err.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
  let output = err._0;
  let errors = FileSystem.writeFiles(output.files);
  if (errors.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        generatedFiles: errors._0,
        diff: undefined,
        warnings: output.warnings
      }
    };
  }
  let message = `Failed to write files: ` + errors._0.join(", ");
  return {
    TAG: "Error",
    _0: {
      TAG: "UnknownError",
      message: message,
      context: undefined
    }
  };
}

function compareSpecsPure(baseSpec, forkSpec, _baseNameOpt, _forkNameOpt) {
  let baseEndpoints = OpenAPIParser.getAllEndpoints(baseSpec);
  let forkEndpoints = OpenAPIParser.getAllEndpoints(forkSpec);
  return SpecDiffer.generateDiff(baseSpec, forkSpec, baseEndpoints, forkEndpoints);
}

async function compareSpecs(baseSpec, forkSpec, baseNameOpt, forkNameOpt, outputPath) {
  let baseName = baseNameOpt !== undefined ? baseNameOpt : "base";
  let forkName = forkNameOpt !== undefined ? forkNameOpt : "fork";
  let diff = compareSpecsPure(baseSpec, forkSpec, baseName, forkName);
  if (outputPath !== undefined) {
    let report = DiffReportGenerator.generateMarkdownReport(diff, baseName, forkName);
    let file = {
      path: outputPath,
      content: report
    };
    FileSystem.writeFile(file);
  }
  return diff;
}

async function generate(config) {
  let baseSpecResult = await SchemaRefResolver.resolve(config.specPath, undefined);
  if (baseSpecResult.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "SpecResolutionError",
        url: config.specPath,
        message: baseSpecResult._0
      }
    };
  }
  let baseSpec = baseSpecResult._0;
  let forkConfigs = config.forkSpecs;
  if (forkConfigs === undefined) {
    return await generateSingleSpec(baseSpec, config);
  }
  if (forkConfigs.length === 0) {
    return await generateSingleSpec(baseSpec, config);
  }
  let forkSpecsPromises = Belt_Array.map(forkConfigs, async forkConfig => {
    let forkSpecResult = await SchemaRefResolver.resolve(forkConfig.specPath, undefined);
    if (forkSpecResult.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          name: forkConfig.name,
          spec: forkSpecResult._0
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: {
          TAG: "SpecResolutionError",
          url: forkConfig.specPath,
          message: `Failed to resolve ` + forkConfig.name + `: ` + forkSpecResult._0
        }
      };
    }
  });
  let forkSpecsResults = await Promise.all(forkSpecsPromises);
  let errors = Belt_Array.keepMap(forkSpecsResults, result => {
    if (result.TAG === "Ok") {
      return;
    } else {
      return result._0;
    }
  });
  if (errors.length !== 0) {
    return {
      TAG: "Error",
      _0: Belt_Array.getExn(errors, 0)
    };
  }
  let forkSpecs = Belt_Array.keepMap(forkSpecsResults, result => {
    if (result.TAG === "Ok") {
      return result._0;
    }
  });
  return await generateMultiSpec(baseSpec, forkSpecs, config);
}

async function generateFromUrl(url, outputDir, config) {
  let defaultConfig = {
    specPath: url,
    forkSpecs: undefined,
    outputDir: outputDir,
    strategy: "SharedBase",
    modulePerTag: true,
    includeTags: undefined,
    excludeTags: undefined,
    generateDiffReport: true,
    breakingChangeHandling: "Warn"
  };
  let finalConfig = Belt_Option.getWithDefault(config, defaultConfig);
  return await generate({
    specPath: url,
    forkSpecs: finalConfig.forkSpecs,
    outputDir: finalConfig.outputDir,
    strategy: finalConfig.strategy,
    modulePerTag: finalConfig.modulePerTag,
    includeTags: finalConfig.includeTags,
    excludeTags: finalConfig.excludeTags,
    generateDiffReport: finalConfig.generateDiffReport,
    breakingChangeHandling: finalConfig.breakingChangeHandling
  });
}

async function generateFromFile(filePath, outputDir, config) {
  let defaultConfig = {
    specPath: filePath,
    forkSpecs: undefined,
    outputDir: outputDir,
    strategy: "SharedBase",
    modulePerTag: true,
    includeTags: undefined,
    excludeTags: undefined,
    generateDiffReport: true,
    breakingChangeHandling: "Warn"
  };
  let finalConfig = Belt_Option.getWithDefault(config, defaultConfig);
  return await generate({
    specPath: filePath,
    forkSpecs: finalConfig.forkSpecs,
    outputDir: finalConfig.outputDir,
    strategy: finalConfig.strategy,
    modulePerTag: finalConfig.modulePerTag,
    includeTags: finalConfig.includeTags,
    excludeTags: finalConfig.excludeTags,
    generateDiffReport: finalConfig.generateDiffReport,
    breakingChangeHandling: finalConfig.breakingChangeHandling
  });
}

let Result;

export {
  Result,
  generateSingleSpecPure,
  generateSingleSpec,
  processForkPure,
  generateMultiSpecPure,
  generateMultiSpec,
  compareSpecsPure,
  compareSpecs,
  generate,
  generateFromUrl,
  generateFromFile,
}
/* FileSystem Not a pure module */
