// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(error) {
  switch (error.TAG) {
    case "SpecResolutionError" :
      return `Failed to resolve spec from '` + error.url + `': ` + error.message;
    case "SchemaParseError" :
      let context = error.context;
      return `Failed to parse schema at '` + context.path + `' (` + context.operation + `): ` + error.reason;
    case "ReferenceError" :
      let context$1 = error.context;
      return `Failed to resolve reference '` + error.ref + `' at '` + context$1.path + `' (` + context$1.operation + `)`;
    case "ValidationError" :
      return `Validation failed for schema '` + error.schema + `': ` + error.issues.join(", ");
    case "CircularSchemaError" :
      return `Circular schema detected for '` + error.ref + `' at depth ` + error.depth.toString() + ` (path: ` + error.path + `)`;
    case "FileWriteError" :
      return `Failed to write file '` + error.filePath + `': ` + error.message;
    case "InvalidConfigError" :
      return `Invalid configuration for field '` + error.field + `': ` + error.message;
    case "UnknownError" :
      let context$2 = error.context;
      let message = error.message;
      if (context$2 !== undefined) {
        return `Unknown error at '` + context$2.path + `' (` + context$2.operation + `): ` + message;
      } else {
        return `Unknown error: ` + message;
      }
  }
}

let toStringError = toString;

let CodegenError = {
  toString: toString,
  toStringError: toStringError
};

function toString$1(warning) {
  switch (warning.TAG) {
    case "FallbackToJson" :
      let context = warning.context;
      return `⚠️  Falling back to JSON.t at '` + context.path + `' (` + context.operation + `): ` + warning.reason;
    case "UnsupportedFeature" :
      return `⚠️  Unsupported feature '` + warning.feature + `' at '` + warning.location + `', using fallback: ` + warning.fallback;
    case "DepthLimitReached" :
      return `⚠️  Depth limit ` + warning.depth.toString() + ` reached at '` + warning.path + `', using simplified type`;
    case "MissingSchema" :
      return `⚠️  Schema reference '` + warning.ref + `' not found at '` + warning.location + `'`;
    case "IntersectionNotFullySupported" :
      return `⚠️  Intersection type at '` + warning.location + `' not fully supported: ` + warning.note;
    case "ComplexUnionSimplified" :
      return `⚠️  Complex union at '` + warning.location + `' simplified (types: ` + warning.types + `)`;
  }
}

function print(warnings) {
  if (warnings.length !== 0) {
    console.log("\n⚠️  Warnings:");
    warnings.forEach(w => {
      console.log(toString$1(w));
    });
    return;
  }
}

let Warning = {
  toString: toString$1,
  print: print
};

export {
  CodegenError,
  Warning,
}
/* No side effect */
