// SPDX-License-Identifier: MIT
// Component Schemas - Shared types and validation schemas
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



module Apiresponse = {
  type t = {
  code: option<int>,
  @as("type") type_: option<string>,
  message: option<string>,
}
  
  let schema = S.object(s => {
    code: s.fieldOr("code", S.nullableAsOption(S.int), None),
    type_: s.fieldOr("type", S.nullableAsOption(S.string), None),
    message: s.fieldOr("message", S.nullableAsOption(S.string), None),
  })
}

module Category = {
  type t = {
  id: option<int>,
  name: option<string>,
}
  
  let schema = S.object(s => {
    id: s.fieldOr("id", S.nullableAsOption(S.int), None),
    name: s.fieldOr("name", S.nullableAsOption(S.string), None),
  })
}

module Order = {
  type t = {
  id: option<int>,
  petid: option<int>,
  quantity: option<int>,
  shipdate: option<string>,
  status: option<string>,
  complete: option<bool>,
}
  
  let schema = S.object(s => {
    id: s.fieldOr("id", S.nullableAsOption(S.int), None),
    petid: s.fieldOr("petId", S.nullableAsOption(S.int), None),
    quantity: s.fieldOr("quantity", S.nullableAsOption(S.int), None),
    shipdate: s.fieldOr("shipDate", S.nullableAsOption(S.string), None),
    status: s.fieldOr("status", S.nullableAsOption(S.string), None),
    complete: s.fieldOr("complete", S.nullableAsOption(S.bool), None),
  })
}

module Pet = {
  type t = {
  id: option<int>,
  name: string,
  category: option<ComponentSchemas.Category.t>,
  photourls: array<string>,
  tags: option<array<ComponentSchemas.Tag.t>>,
  status: option<string>,
}
  
  let schema = S.object(s => {
    id: s.fieldOr("id", S.nullableAsOption(S.int), None),
    name: s.field("name", S.string),
    category: s.fieldOr("category", S.nullableAsOption(ComponentSchemas.Category.schema), None),
    photourls: s.field("photoUrls", S.array(S.string)),
    tags: s.fieldOr("tags", S.nullableAsOption(S.array(ComponentSchemas.Tag.schema)), None),
    status: s.fieldOr("status", S.nullableAsOption(S.string), None),
  })
}

module Tag = {
  type t = {
  id: option<int>,
  name: option<string>,
}
  
  let schema = S.object(s => {
    id: s.fieldOr("id", S.nullableAsOption(S.int), None),
    name: s.fieldOr("name", S.nullableAsOption(S.string), None),
  })
}

module User = {
  type t = {
  id: option<int>,
  username: option<string>,
  firstname: option<string>,
  lastname: option<string>,
  email: option<string>,
  password: option<string>,
  phone: option<string>,
  userstatus: option<int>,
}
  
  let schema = S.object(s => {
    id: s.fieldOr("id", S.nullableAsOption(S.int), None),
    username: s.fieldOr("username", S.nullableAsOption(S.string), None),
    firstname: s.fieldOr("firstName", S.nullableAsOption(S.string), None),
    lastname: s.fieldOr("lastName", S.nullableAsOption(S.string), None),
    email: s.fieldOr("email", S.nullableAsOption(S.string), None),
    password: s.fieldOr("password", S.nullableAsOption(S.string), None),
    phone: s.fieldOr("phone", S.nullableAsOption(S.string), None),
    userstatus: s.fieldOr("userStatus", S.nullableAsOption(S.int), None),
  })
}
