// SPDX-License-Identifier: MIT
// API endpoints for pet
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



module Pet = {
    type addpetRequest = JSON.t

    let addpetRequestSchema = S.json

    type addpetResponse = JSON.t

    let addpetResponseSchema = S.json

    // Add a new pet to the store.
    let addpet = (~body, ~fetch): promise<addpetResponse> => {
      let validatedBody = addpetRequestSchema->S.parseOrThrow(body)

      fetch(
        ~url="/pet",
        ~method_="POST",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = addpetResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type updatepetRequest = JSON.t

    let updatepetRequestSchema = S.json

    type updatepetResponse = JSON.t

    let updatepetResponseSchema = S.json

    // Update an existing pet.
    let updatepet = (~body, ~fetch): promise<updatepetResponse> => {
      let validatedBody = updatepetRequestSchema->S.parseOrThrow(body)

      fetch(
        ~url="/pet",
        ~method_="PUT",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = updatepetResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type findpetsbystatusResponse = array<ComponentSchemas.Pet.t>

    let findpetsbystatusResponseSchema = S.array(ComponentSchemas.Pet.schema)

    // Finds Pets by status.
    let findpetsbystatus = (~fetch): promise<findpetsbystatusResponse> => {
      // query parameter: status

      fetch(
        ~url="/pet/findByStatus",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = findpetsbystatusResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type findpetsbytagsResponse = array<ComponentSchemas.Pet.t>

    let findpetsbytagsResponseSchema = S.array(ComponentSchemas.Pet.schema)

    // Finds Pets by tags.
    let findpetsbytags = (~fetch): promise<findpetsbytagsResponse> => {
      // query parameter: tags

      fetch(
        ~url="/pet/findByTags",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = findpetsbytagsResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type getpetbyidResponse = JSON.t

    let getpetbyidResponseSchema = S.json

    // Find pet by ID.
    let getpetbyid = (~fetch): promise<getpetbyidResponse> => {
      // path parameter: petId

      fetch(
        ~url="/pet/{petId}",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = getpetbyidResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type updatepetwithformResponse = JSON.t

    let updatepetwithformResponseSchema = S.json

    // Updates a pet in the store with form data.
    let updatepetwithform = (~fetch): promise<updatepetwithformResponse> => {
      // path parameter: petId
      // query parameter: name
      // query parameter: status

      fetch(
        ~url="/pet/{petId}",
        ~method_="POST",
      )->Promise.then(response => {
      let validatedResponse = updatepetwithformResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type deletepetResponse = unit

    // Deletes a pet.
    let deletepet = (~fetch): promise<deletepetResponse> => {
      // header parameter: api_key
      // path parameter: petId

      fetch(
        ~url="/pet/{petId}",
        ~method_="DELETE",
      )->Promise.then(response => {
      response
    ->Promise.resolve
      })
    }

    type uploadfileRequest = string

    let uploadfileRequestSchema = S.string

    type uploadfileResponse = JSON.t

    let uploadfileResponseSchema = S.json

    // Uploads an image.
    let uploadfile = (~body=?, ~fetch): promise<uploadfileResponse> => {
      // path parameter: petId
      // query parameter: additionalMetadata
      let validatedBody = body->Belt.Option.map(b => uploadfileRequestSchema->S.parseOrThrow(b))

      fetch(
        ~url="/pet/{petId}/uploadImage",
        ~method_="POST",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = uploadfileResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

}