// SPDX-License-Identifier: MIT
// API endpoints for store
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



module Store = {
    type getinventoryResponse = JSON.t

    let getinventoryResponseSchema = S.json

    // Returns pet inventories by status.
    let getinventory = (~fetch): promise<getinventoryResponse> => {

      fetch(
        ~url="/store/inventory",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = getinventoryResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type placeorderRequest = ComponentSchemas.Order.t

    let placeorderRequestSchema = ComponentSchemas.Order.schema

    type placeorderResponse = ComponentSchemas.Order.t

    let placeorderResponseSchema = ComponentSchemas.Order.schema

    // Place an order for a pet.
    let placeorder = (~body=?, ~fetch): promise<placeorderResponse> => {
      let validatedBody = body->Belt.Option.map(b => placeorderRequestSchema->S.parseOrThrow(b))

      fetch(
        ~url="/store/order",
        ~method_="POST",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = placeorderResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type getorderbyidResponse = ComponentSchemas.Order.t

    let getorderbyidResponseSchema = ComponentSchemas.Order.schema

    // Find purchase order by ID.
    let getorderbyid = (~fetch): promise<getorderbyidResponse> => {
      // path parameter: orderId

      fetch(
        ~url="/store/order/{orderId}",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = getorderbyidResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type deleteorderResponse = unit

    // Delete purchase order by identifier.
    let deleteorder = (~fetch): promise<deleteorderResponse> => {
      // path parameter: orderId

      fetch(
        ~url="/store/order/{orderId}",
        ~method_="DELETE",
      )->Promise.then(response => {
      response
    ->Promise.resolve
      })
    }

}