// SPDX-License-Identifier: MIT
// API endpoints for user
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated



module User = {
    type createuserRequest = ComponentSchemas.User.t

    let createuserRequestSchema = ComponentSchemas.User.schema

    type createuserResponse = ComponentSchemas.User.t

    let createuserResponseSchema = ComponentSchemas.User.schema

    // Create user.
    let createuser = (~body=?, ~fetch): promise<createuserResponse> => {
      let validatedBody = body->Belt.Option.map(b => createuserRequestSchema->S.parseOrThrow(b))

      fetch(
        ~url="/user",
        ~method_="POST",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = createuserResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type createuserswithlistinputRequest = array<ComponentSchemas.User.t>

    let createuserswithlistinputRequestSchema = S.array(ComponentSchemas.User.schema)

    type createuserswithlistinputResponse = ComponentSchemas.User.t

    let createuserswithlistinputResponseSchema = ComponentSchemas.User.schema

    // Creates list of users with given input array.
    let createuserswithlistinput = (~body=?, ~fetch): promise<createuserswithlistinputResponse> => {
      let validatedBody = body->Belt.Option.map(b => createuserswithlistinputRequestSchema->S.parseOrThrow(b))

      fetch(
        ~url="/user/createWithList",
        ~method_="POST",
        ~body=validatedBody,
      )->Promise.then(response => {
      let validatedResponse = createuserswithlistinputResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type loginuserResponse = string

    let loginuserResponseSchema = S.string

    // Logs user into the system.
    let loginuser = (~fetch): promise<loginuserResponse> => {
      // query parameter: username
      // query parameter: password

      fetch(
        ~url="/user/login",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = loginuserResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type logoutuserResponse = unit

    // Logs out current logged in user session.
    let logoutuser = (~fetch): promise<logoutuserResponse> => {

      fetch(
        ~url="/user/logout",
        ~method_="GET",
      )->Promise.then(response => {
      response
    ->Promise.resolve
      })
    }

    type getuserbynameResponse = ComponentSchemas.User.t

    let getuserbynameResponseSchema = ComponentSchemas.User.schema

    // Get user by user name.
    let getuserbyname = (~fetch): promise<getuserbynameResponse> => {
      // path parameter: username

      fetch(
        ~url="/user/{username}",
        ~method_="GET",
      )->Promise.then(response => {
      let validatedResponse = getuserbynameResponseSchema->S.parseOrThrow(response)
      validatedResponse
    ->Promise.resolve
      })
    }

    type updateuserRequest = ComponentSchemas.User.t

    let updateuserRequestSchema = ComponentSchemas.User.schema

    type updateuserResponse = unit

    // Update user resource.
    let updateuser = (~body=?, ~fetch): promise<updateuserResponse> => {
      // path parameter: username
      let validatedBody = body->Belt.Option.map(b => updateuserRequestSchema->S.parseOrThrow(b))

      fetch(
        ~url="/user/{username}",
        ~method_="PUT",
        ~body=validatedBody,
      )->Promise.then(response => {
      response
    ->Promise.resolve
      })
    }

    type deleteuserResponse = unit

    // Delete user resource.
    let deleteuser = (~fetch): promise<deleteuserResponse> => {
      // path parameter: username

      fetch(
        ~url="/user/{username}",
        ~method_="DELETE",
      )->Promise.then(response => {
      response
    ->Promise.resolve
      })
    }

}